package com.xiaoan.wlt.model.base;

import com.xiaoan.wlt.common.jfinal.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStatSaleTotMonth<M extends BaseStatSaleTotMonth<M>> extends BaseModel<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setMonths(java.lang.String months) {
		set("months", months);
	}

	public java.lang.String getMonths() {
		return get("months");
	}

	public void setScode(java.lang.String scode) {
		set("scode", scode);
	}

	public java.lang.String getScode() {
		return get("scode");
	}

	public void setScodeName(java.lang.String scodeName) {
		set("scodeName", scodeName);
	}

	public java.lang.String getScodeName() {
		return get("scodeName");
	}

	public void setWechatNum(java.lang.Integer wechatNum) {
		set("wechat_num", wechatNum);
	}

	public java.lang.Integer getWechatNum() {
		return get("wechat_num");
	}

	public void setWechatBuy(java.lang.Integer wechatBuy) {
		set("wechat_buy", wechatBuy);
	}

	public java.lang.Integer getWechatBuy() {
		return get("wechat_buy");
	}

	public void setWillNum(java.lang.Integer willNum) {
		set("will_num", willNum);
	}

	public java.lang.Integer getWillNum() {
		return get("will_num");
	}

	public void setWillBuy(java.lang.Integer willBuy) {
		set("will_buy", willBuy);
	}

	public java.lang.Integer getWillBuy() {
		return get("will_buy");
	}

	public void setInstallNum(java.lang.Integer installNum) {
		set("install_num", installNum);
	}

	public java.lang.Integer getInstallNum() {
		return get("install_num");
	}

	public void setBuy0(java.lang.Integer buy0) {
		set("buy0", buy0);
	}

	public java.lang.Integer getBuy0() {
		return get("buy0");
	}

	public void setBuy1(java.lang.Integer buy1) {
		set("buy1", buy1);
	}

	public java.lang.Integer getBuy1() {
		return get("buy1");
	}

	public void setBuy2(java.lang.Integer buy2) {
		set("buy2", buy2);
	}

	public java.lang.Integer getBuy2() {
		return get("buy2");
	}

	public void setBuy35(java.lang.Integer buy35) {
		set("buy3_5", buy35);
	}

	public java.lang.Integer getBuy35() {
		return get("buy3_5");
	}

	public void setBuy6(java.lang.Integer buy6) {
		set("buy6", buy6);
	}

	public java.lang.Integer getBuy6() {
		return get("buy6");
	}

	public void setBuyn1(java.lang.Integer buyn1) {
		set("buyn1", buyn1);
	}

	public java.lang.Integer getBuyn1() {
		return get("buyn1");
	}

	public void setBuyn2(java.lang.Integer buyn2) {
		set("buyn2", buyn2);
	}

	public java.lang.Integer getBuyn2() {
		return get("buyn2");
	}

	public void setBuyn35(java.lang.Integer buyn35) {
		set("buyn3_5", buyn35);
	}

	public java.lang.Integer getBuyn35() {
		return get("buyn3_5");
	}

	public void setBuyn6(java.lang.Integer buyn6) {
		set("buyn6", buyn6);
	}

	public java.lang.Integer getBuyn6() {
		return get("buyn6");
	}

	public void setCurNewShops(java.lang.Integer curNewShops) {
		set("cur_new_shops", curNewShops);
	}

	public java.lang.Integer getCurNewShops() {
		return get("cur_new_shops");
	}

	public void setCurNewShopsBuyn(java.lang.Integer curNewShopsBuyn) {
		set("cur_new_shops_buyn", curNewShopsBuyn);
	}

	public java.lang.Integer getCurNewShopsBuyn() {
		return get("cur_new_shops_buyn");
	}

	public void setCurOldShops(java.lang.Integer curOldShops) {
		set("cur_old_shops", curOldShops);
	}

	public java.lang.Integer getCurOldShops() {
		return get("cur_old_shops");
	}

	public void setCurOldShopsBuyn(java.lang.Integer curOldShopsBuyn) {
		set("cur_old_shops_buyn", curOldShopsBuyn);
	}

	public java.lang.Integer getCurOldShopsBuyn() {
		return get("cur_old_shops_buyn");
	}

	public void setCurOrderInstall(java.lang.Integer curOrderInstall) {
		set("cur_order_install", curOrderInstall);
	}

	public java.lang.Integer getCurOrderInstall() {
		return get("cur_order_install");
	}

	public void setCurBuy2Month(java.lang.Integer curBuy2Month) {
		set("cur_buy2_month", curBuy2Month);
	}

	public java.lang.Integer getCurBuy2Month() {
		return get("cur_buy2_month");
	}

	public void setCurBuy3Month(java.lang.Integer curBuy3Month) {
		set("cur_buy3_month", curBuy3Month);
	}

	public java.lang.Integer getCurBuy3Month() {
		return get("cur_buy3_month");
	}

	public void setCurBuy4Month(java.lang.Integer curBuy4Month) {
		set("cur_buy4_month", curBuy4Month);
	}

	public java.lang.Integer getCurBuy4Month() {
		return get("cur_buy4_month");
	}

	public void setCurMaterielNum(java.lang.Integer curMaterielNum) {
		set("cur_materiel_num", curMaterielNum);
	}

	public java.lang.Integer getCurMaterielNum() {
		return get("cur_materiel_num");
	}

	public void setCurNewWechat(java.lang.Integer curNewWechat) {
		set("cur_new_wechat", curNewWechat);
	}

	public java.lang.Integer getCurNewWechat() {
		return get("cur_new_wechat");
	}

	public void setCurNewWill(java.lang.Integer curNewWill) {
		set("cur_new_will", curNewWill);
	}

	public java.lang.Integer getCurNewWill() {
		return get("cur_new_will");
	}

	public void setCurNewBuy(java.lang.Integer curNewBuy) {
		set("cur_new_buy", curNewBuy);
	}

	public java.lang.Integer getCurNewBuy() {
		return get("cur_new_buy");
	}

	public void setCurCommTimes(java.lang.Integer curCommTimes) {
		set("cur_comm_times", curCommTimes);
	}

	public java.lang.Integer getCurCommTimes() {
		return get("cur_comm_times");
	}

	public void setCurCommNum(java.lang.Integer curCommNum) {
		set("cur_comm_num", curCommNum);
	}

	public java.lang.Integer getCurCommNum() {
		return get("cur_comm_num");
	}

}
