package com.xiaoan.wlt.model.sys;

import org.apache.commons.lang3.StringUtils;

import com.xiaoan.wlt.common.WhereAndParas;

import java.util.ArrayList;

import java.util.List;

import com.jfinal.plugin.activerecord.Page;

import com.xiaoan.wlt.model.base.sys.BaseRolePath;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RolePath extends BaseRolePath<RolePath> {
	public static final RolePath dao = new RolePath();
	private int pageNumber = 1;
	private int pageSize = 15;
	public int getPageSize() {return pageSize;}
	public void setPageSize(int pageSize) {this.pageSize = pageSize;}
	public int getPageNumber() {return pageNumber;}
	public void setPageNumber(int pageNumber) {this.pageNumber = pageNumber;}
	public Page<RolePath> findPageList(RolePath rolePath) {
		WhereAndParas wp = getWhereAndParas(rolePath);
		return dao.paginate(rolePath.getPageNumber(),rolePath.getPageSize(),"select * ","from"+ RolePath.TABLE + "where 1=1 " +wp.getWhere(),wp.getParas());
	}
	public static final String TABLE = " sys_role_path ";
	public WhereAndParas getWhereAndParas(RolePath rolePath){
		StringBuffer sql = new StringBuffer();
		List<Object> list = new ArrayList<Object>();
		WhereAndParas wap = new WhereAndParas();
		if(rolePath.getId() != null && rolePath.getId() > 0){
			sql.append(" and id = ?");
			list.add(rolePath.getId());
		}
		if(rolePath.getVersion() != null && rolePath.getVersion() > 0){
			sql.append(" and version = ?");
			list.add(rolePath.getVersion());
		}
		if(StringUtils.isNotEmpty(rolePath.getFunctionCde())){
			sql.append(" and functionCde like ?");
			list.add("%"+rolePath.getFunctionCde()+"%");
		}
		if(StringUtils.isNotEmpty(rolePath.getPath())){
			sql.append(" and path like ?");
			list.add("%"+rolePath.getPath()+"%");
		}
		if(rolePath.getRoleId() != null && rolePath.getRoleId() > 0){
			sql.append(" and roleId = ?");
			list.add(rolePath.getRoleId());
		}
		wap.setWhere(sql.toString());
		wap.setParas(list.toArray());
		return wap;
	}
}
