package com.xiaoan.wlt.model.sys;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import com.jfinal.plugin.activerecord.Page;
import com.xiaoan.wlt.common.WhereAndParas;
import com.xiaoan.wlt.model.base.sys.BaseRoleUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RoleUser extends BaseRoleUser<RoleUser> {
	public static final RoleUser dao = new RoleUser();
	private int pageNumber = 1;
	private int pageSize = 15;
	public int getPageSize() {return pageSize;}
	public void setPageSize(int pageSize) {this.pageSize = pageSize;}
	public int getPageNumber() {return pageNumber;}
	public void setPageNumber(int pageNumber) {this.pageNumber = pageNumber;}
	public Page<RoleUser> findPageList(RoleUser roleUser) {
		WhereAndParas wp = getWhereAndParas(roleUser);
		return dao.paginate(roleUser.getPageNumber(),roleUser.getPageSize(),"select * ","from"+ RoleUser.TABLE + "where 1=1 " +wp.getWhere(),wp.getParas());
	}
	public static final String TABLE = " sys_role_user ";
	public WhereAndParas getWhereAndParas(RoleUser roleUser){
		StringBuffer sql = new StringBuffer();
		List<Object> list = new ArrayList<Object>();
		WhereAndParas wap = new WhereAndParas();
		if(roleUser.getId() != null && roleUser.getId() > 0){
			sql.append(" and id = ?");
			list.add(roleUser.getId());
		}
		if(roleUser.getVersion() != null && roleUser.getVersion() > 0){
			sql.append(" and version = ?");
			list.add(roleUser.getVersion());
		}
		if(roleUser.getRoleId() != null && roleUser.getRoleId() > 0){
			sql.append(" and roleId = ?");
			list.add(roleUser.getRoleId());
		}
		if(roleUser.getUserId() != null && roleUser.getUserId() > 0){
			sql.append(" and userId = ?");
			list.add(roleUser.getUserId());
		}
		wap.setWhere(sql.toString());
		wap.setParas(list.toArray());
		return wap;
	}
	public void updateRoleUser(String roleId, String userIds) {
		for(String userId : userIds.split(",")){
			List<RoleUser> list = RoleUser.dao.find("select * from sys_role_user where roleId=? and userId=?",roleId,userId);
			if(list == null || list.size() == 0){
				RoleUser ru = new RoleUser();
				ru.setUserId(Long.parseLong(userId));
				ru.setRoleId(Long.parseLong(roleId));
				ru.setCreateTime(new Date());
				ru.setUpdateTime(new Date());
				ru.save();
			}
		}
	}
	public List<RoleUser> getUserRoles(String userId) {
		return RoleUser.dao.find("select * from sys_role_user where userId = ?",userId);
	}
}
