package com.xiaoan.wlt.model.zyk;

import org.apache.commons.lang3.StringUtils;

import com.xiaoan.wlt.common.WhereAndParas;

import java.util.ArrayList;

import java.util.List;

import com.jfinal.plugin.activerecord.Page;

import com.xiaoan.wlt.model.base.zyk.BaseActLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActLog extends BaseActLog<ActLog> {
	public static final ActLog dao = new ActLog();
}
