package com.xiaoan.wlt.model.zyk;

import java.util.List;

import org.apache.commons.lang3.StringUtils;

import com.xiaoan.wlt.model.base.zyk.BaseCategory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Category extends BaseCategory<Category> {
	public static final Category dao = new Category();

	/**
	 * 获取除指定id之外的Category列表
	 * 
	 * @param id
	 * @return
	 */
	public List<Category> getCatList(String id) {
		String sql = null;
		if (StringUtils.isNoneBlank(id)) {
			sql = "select * from " + getTable().getName()
					+ " where state='USE' and id <> ? order by idx";
			return find(sql, id);
		} else {
			sql = "select * from " + getTable().getName()
					+ " where state='USE' order by idx";
			return find(sql);
		}
	}

	public List<Category> getAllCats() {
		return getCatList(null);
	}
}
