package com.xiaoan.wlt.model.zyk;

import java.util.List;

import com.xiaoan.wlt.model.base.zyk.BaseResourceTemplate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ResourceTemplate extends BaseResourceTemplate<ResourceTemplate> {
	public static final ResourceTemplate dao = new ResourceTemplate();

	public Category getCat() {
		return Category.dao.findById(get("category"));
	}

	public List<ResourceTemplate> getAll() {
		// TODO Auto-generated method stub
		return null;
	}
}
