package com.xiaoan.wlt.model.base.sys;

import com.xiaoan.wlt.common.jfinal.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

import org.apache.commons.lang3.StringUtils;

import com.xiaoan.wlt.common.WhereAndParas;

import java.util.ArrayList;

import java.util.List;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRolePerm<M extends BaseRolePerm<M>> extends BaseModel<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public void setVersion(java.lang.Integer version) {
		set("version", version);
	}

	public java.lang.Integer getVersion() {
		return get("version");
	}

	public void setFunctionId(java.lang.String functionId) {
		set("functionId", functionId);
	}

	public java.lang.String getFunctionId() {
		return get("functionId");
	}

	public void setRoleId(java.lang.Long roleId) {
		set("roleId", roleId);
	}

	public java.lang.Long getRoleId() {
		return get("roleId");
	}

	public static final String TABLE = " sys_role_perm ";
	public WhereAndParas getWhereAndParas(BaseRolePerm rolePerm){
		StringBuffer sql = new StringBuffer();
		List<Object> list = new ArrayList<Object>();
		WhereAndParas wap = new WhereAndParas();
		if(rolePerm.getId() != null && rolePerm.getId() > 0){
			sql.append(" and o.id = ?");
			list.add(rolePerm.getId());
		}
		if(rolePerm.getVersion() != null && rolePerm.getVersion() > 0){
			sql.append(" and o.version = ?");
			list.add(rolePerm.getVersion());
		}
		if(StringUtils.isNotEmpty(rolePerm.getFunctionId())){
			sql.append(" and o.functionId like ?");
			list.add("%"+rolePerm.getFunctionId()+"%");
		}
		if(rolePerm.getRoleId() != null && rolePerm.getRoleId() > 0){
			sql.append(" and o.roleId = ?");
			list.add(rolePerm.getRoleId());
		}
		wap.setWhere(sql.toString());
		wap.setParas(list.toArray());
		return wap;
	}
}
