package com.xiaoan.wlt.model.base.sys;

import com.xiaoan.wlt.common.jfinal.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

import org.apache.commons.lang3.StringUtils;

import com.xiaoan.wlt.common.WhereAndParas;

import java.util.ArrayList;

import java.util.List;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRoleUser<M extends BaseRoleUser<M>> extends BaseModel<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public void setVersion(java.lang.Integer version) {
		set("version", version);
	}

	public java.lang.Integer getVersion() {
		return get("version");
	}

	public void setRoleId(java.lang.Long roleId) {
		set("roleId", roleId);
	}

	public java.lang.Long getRoleId() {
		return get("roleId");
	}

	public void setUserId(java.lang.Long userId) {
		set("userId", userId);
	}

	public java.lang.Long getUserId() {
		return get("userId");
	}

	public static final String TABLE = " sys_role_user ";
	public WhereAndParas getWhereAndParas(BaseRoleUser roleUser){
		StringBuffer sql = new StringBuffer();
		List<Object> list = new ArrayList<Object>();
		WhereAndParas wap = new WhereAndParas();
		if(roleUser.getId() != null && roleUser.getId() > 0){
			sql.append(" and o.id = ?");
			list.add(roleUser.getId());
		}
		if(roleUser.getVersion() != null && roleUser.getVersion() > 0){
			sql.append(" and o.version = ?");
			list.add(roleUser.getVersion());
		}
		if(roleUser.getRoleId() != null && roleUser.getRoleId() > 0){
			sql.append(" and o.roleId = ?");
			list.add(roleUser.getRoleId());
		}
		if(roleUser.getUserId() != null && roleUser.getUserId() > 0){
			sql.append(" and o.userId = ?");
			list.add(roleUser.getUserId());
		}
		wap.setWhere(sql.toString());
		wap.setParas(list.toArray());
		return wap;
	}
}
