package com.xiaoan.wlt.model.base;

import com.xiaoan.wlt.common.jfinal.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStatSaleMonthTarget<M extends BaseStatSaleMonthTarget<M>> extends BaseModel<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public void setVersion(java.lang.Integer version) {
		set("version", version);
	}

	public java.lang.Integer getVersion() {
		return get("version");
	}

	public void setMonths(java.lang.String months) {
		set("months", months);
	}

	public java.lang.String getMonths() {
		return get("months");
	}

	public void setSalesId(java.lang.Long salesId) {
		set("salesId", salesId);
	}

	public java.lang.Long getSalesId() {
		return get("salesId");
	}

	public void setScode(java.lang.String scode) {
		set("scode", scode);
	}

	public java.lang.String getScode() {
		return get("scode");
	}

	public void setTargetType(java.lang.String targetType) {
		set("targetType", targetType);
	}

	public java.lang.String getTargetType() {
		return get("targetType");
	}

	public void setTargetValue(java.lang.String targetValue) {
		set("targetValue", targetValue);
	}

	public java.lang.String getTargetValue() {
		return get("targetValue");
	}

	public void setCommNum(java.lang.String commNum) {
		set("commNum", commNum);
	}

	public java.lang.String getCommNum() {
		return get("commNum");
	}

}
