package com.xiaoan.wlt.model.base;

import com.xiaoan.wlt.common.jfinal.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCustAccount<M extends BaseCustAccount<M>> extends BaseModel<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public void setVersion(java.lang.Integer version) {
		set("version", version);
	}

	public java.lang.Integer getVersion() {
		return get("version");
	}

	public void setAppKey(java.lang.String appKey) {
		set("appKey", appKey);
	}

	public java.lang.String getAppKey() {
		return get("appKey");
	}

	public void setCustAccount(java.lang.String custAccount) {
		set("custAccount", custAccount);
	}

	public java.lang.String getCustAccount() {
		return get("custAccount");
	}

	public void setOrgPermkey(java.lang.String orgPermkey) {
		set("orgPermkey", orgPermkey);
	}

	public java.lang.String getOrgPermkey() {
		return get("orgPermkey");
	}

	public void setOrgTempKey(java.lang.String orgTempKey) {
		set("orgTempKey", orgTempKey);
	}

	public java.lang.String getOrgTempKey() {
		return get("orgTempKey");
	}

	public void setState(java.lang.String state) {
		set("state", state);
	}

	public java.lang.String getState() {
		return get("state");
	}

	public void setUserId(java.lang.Long userId) {
		set("userId", userId);
	}

	public java.lang.Long getUserId() {
		return get("userId");
	}

}
