package com.xiaoan.wlt.model.t;

import org.apache.commons.lang3.StringUtils;

import com.xiaoan.wlt.common.WhereAndParas;

import java.util.ArrayList;

import java.util.List;

import com.jfinal.plugin.activerecord.Page;

import com.xiaoan.wlt.model.base.t.BaseStatSaleTotMonth;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StatSaleTotMonth extends BaseStatSaleTotMonth<StatSaleTotMonth> {
	public static final StatSaleTotMonth dao = new StatSaleTotMonth();
	private int pageNumber = 1;
	private int pageSize = 15;
	public int getPageSize() {return pageSize;}
	public void setPageSize(int pageSize) {this.pageSize = pageSize;}
	public int getPageNumber() {return pageNumber;}
	public void setPageNumber(int pageNumber) {this.pageNumber = pageNumber;}
	public Page<StatSaleTotMonth> findPageList(StatSaleTotMonth statSaleTotMonth) {
		WhereAndParas wp = getWhereAndParas(statSaleTotMonth);
		return dao.paginate(statSaleTotMonth.getPageNumber(),statSaleTotMonth.getPageSize(),"select * ","from"+ StatSaleTotMonth.TABLE + "where 1=1 " +wp.getWhere(),wp.getParas());
	}
	public static final String TABLE = " t_stat_sale_tot_month ";
	public WhereAndParas getWhereAndParas(StatSaleTotMonth statSaleTotMonth){
		StringBuffer sql = new StringBuffer();
		List<Object> list = new ArrayList<Object>();
		WhereAndParas wap = new WhereAndParas();
		if(statSaleTotMonth.getId() != null && statSaleTotMonth.getId() > 0){
			sql.append(" and id = ?");
			list.add(statSaleTotMonth.getId());
		}
		if(StringUtils.isNotEmpty(statSaleTotMonth.getMonths())){
			sql.append(" and months like ?");
			list.add("%"+statSaleTotMonth.getMonths()+"%");
		}
		if(StringUtils.isNotEmpty(statSaleTotMonth.getScode())){
			sql.append(" and scode like ?");
			list.add("%"+statSaleTotMonth.getScode()+"%");
		}
		if(StringUtils.isNotEmpty(statSaleTotMonth.getScodeName())){
			sql.append(" and scodeName like ?");
			list.add("%"+statSaleTotMonth.getScodeName()+"%");
		}
		if(statSaleTotMonth.getWechatNum() != null && statSaleTotMonth.getWechatNum() > 0){
			sql.append(" and wechatNum = ?");
			list.add(statSaleTotMonth.getWechatNum());
		}
		if(statSaleTotMonth.getWechatBuy() != null && statSaleTotMonth.getWechatBuy() > 0){
			sql.append(" and wechatBuy = ?");
			list.add(statSaleTotMonth.getWechatBuy());
		}
		if(statSaleTotMonth.getWillNum() != null && statSaleTotMonth.getWillNum() > 0){
			sql.append(" and willNum = ?");
			list.add(statSaleTotMonth.getWillNum());
		}
		if(statSaleTotMonth.getWillBuy() != null && statSaleTotMonth.getWillBuy() > 0){
			sql.append(" and willBuy = ?");
			list.add(statSaleTotMonth.getWillBuy());
		}
		if(statSaleTotMonth.getInstallNum() != null && statSaleTotMonth.getInstallNum() > 0){
			sql.append(" and installNum = ?");
			list.add(statSaleTotMonth.getInstallNum());
		}
		if(statSaleTotMonth.getBuy0() != null && statSaleTotMonth.getBuy0() > 0){
			sql.append(" and buy0 = ?");
			list.add(statSaleTotMonth.getBuy0());
		}
		if(statSaleTotMonth.getBuy1() != null && statSaleTotMonth.getBuy1() > 0){
			sql.append(" and buy1 = ?");
			list.add(statSaleTotMonth.getBuy1());
		}
		if(statSaleTotMonth.getBuy2() != null && statSaleTotMonth.getBuy2() > 0){
			sql.append(" and buy2 = ?");
			list.add(statSaleTotMonth.getBuy2());
		}
		if(statSaleTotMonth.getBuy35() != null && statSaleTotMonth.getBuy35() > 0){
			sql.append(" and buy35 = ?");
			list.add(statSaleTotMonth.getBuy35());
		}
		if(statSaleTotMonth.getBuy6() != null && statSaleTotMonth.getBuy6() > 0){
			sql.append(" and buy6 = ?");
			list.add(statSaleTotMonth.getBuy6());
		}
		if(statSaleTotMonth.getBuyn1() != null && statSaleTotMonth.getBuyn1() > 0){
			sql.append(" and buyn1 = ?");
			list.add(statSaleTotMonth.getBuyn1());
		}
		if(statSaleTotMonth.getBuyn2() != null && statSaleTotMonth.getBuyn2() > 0){
			sql.append(" and buyn2 = ?");
			list.add(statSaleTotMonth.getBuyn2());
		}
		if(statSaleTotMonth.getBuyn35() != null && statSaleTotMonth.getBuyn35() > 0){
			sql.append(" and buyn35 = ?");
			list.add(statSaleTotMonth.getBuyn35());
		}
		if(statSaleTotMonth.getBuyn6() != null && statSaleTotMonth.getBuyn6() > 0){
			sql.append(" and buyn6 = ?");
			list.add(statSaleTotMonth.getBuyn6());
		}
		if(statSaleTotMonth.getCurNewShops() != null && statSaleTotMonth.getCurNewShops() > 0){
			sql.append(" and curNewShops = ?");
			list.add(statSaleTotMonth.getCurNewShops());
		}
		if(statSaleTotMonth.getCurNewShopsBuyn() != null && statSaleTotMonth.getCurNewShopsBuyn() > 0){
			sql.append(" and curNewShopsBuyn = ?");
			list.add(statSaleTotMonth.getCurNewShopsBuyn());
		}
		if(statSaleTotMonth.getCurOldShops() != null && statSaleTotMonth.getCurOldShops() > 0){
			sql.append(" and curOldShops = ?");
			list.add(statSaleTotMonth.getCurOldShops());
		}
		if(statSaleTotMonth.getCurOldShopsBuyn() != null && statSaleTotMonth.getCurOldShopsBuyn() > 0){
			sql.append(" and curOldShopsBuyn = ?");
			list.add(statSaleTotMonth.getCurOldShopsBuyn());
		}
		if(statSaleTotMonth.getCurOrderInstall() != null && statSaleTotMonth.getCurOrderInstall() > 0){
			sql.append(" and curOrderInstall = ?");
			list.add(statSaleTotMonth.getCurOrderInstall());
		}
		if(statSaleTotMonth.getCurBuy2Month() != null && statSaleTotMonth.getCurBuy2Month() > 0){
			sql.append(" and curBuy2Month = ?");
			list.add(statSaleTotMonth.getCurBuy2Month());
		}
		if(statSaleTotMonth.getCurBuy3Month() != null && statSaleTotMonth.getCurBuy3Month() > 0){
			sql.append(" and curBuy3Month = ?");
			list.add(statSaleTotMonth.getCurBuy3Month());
		}
		if(statSaleTotMonth.getCurBuy4Month() != null && statSaleTotMonth.getCurBuy4Month() > 0){
			sql.append(" and curBuy4Month = ?");
			list.add(statSaleTotMonth.getCurBuy4Month());
		}
		if(statSaleTotMonth.getCurMaterielNum() != null && statSaleTotMonth.getCurMaterielNum() > 0){
			sql.append(" and curMaterielNum = ?");
			list.add(statSaleTotMonth.getCurMaterielNum());
		}
		if(statSaleTotMonth.getCurNewWechat() != null && statSaleTotMonth.getCurNewWechat() > 0){
			sql.append(" and curNewWechat = ?");
			list.add(statSaleTotMonth.getCurNewWechat());
		}
		if(statSaleTotMonth.getCurNewWill() != null && statSaleTotMonth.getCurNewWill() > 0){
			sql.append(" and curNewWill = ?");
			list.add(statSaleTotMonth.getCurNewWill());
		}
		if(statSaleTotMonth.getCurNewBuy() != null && statSaleTotMonth.getCurNewBuy() > 0){
			sql.append(" and curNewBuy = ?");
			list.add(statSaleTotMonth.getCurNewBuy());
		}
		if(statSaleTotMonth.getCurCommTimes() != null && statSaleTotMonth.getCurCommTimes() > 0){
			sql.append(" and curCommTimes = ?");
			list.add(statSaleTotMonth.getCurCommTimes());
		}
		if(statSaleTotMonth.getCurCommNum() != null && statSaleTotMonth.getCurCommNum() > 0){
			sql.append(" and curCommNum = ?");
			list.add(statSaleTotMonth.getCurCommNum());
		}
		wap.setWhere(sql.toString());
		wap.setParas(list.toArray());
		return wap;
	}
}
