package com.xiaoan.wlt.model.t;

import org.apache.commons.lang3.StringUtils;

import com.xiaoan.wlt.common.WhereAndParas;

import java.util.ArrayList;

import java.util.List;

import com.jfinal.plugin.activerecord.Page;

import com.xiaoan.wlt.model.base.t.BaseWechatUsers;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WechatUsers extends BaseWechatUsers<WechatUsers> {
	public static final WechatUsers dao = new WechatUsers();
	private int pageNumber = 1;
	private int pageSize = 15;
	public int getPageSize() {return pageSize;}
	public void setPageSize(int pageSize) {this.pageSize = pageSize;}
	public int getPageNumber() {return pageNumber;}
	public void setPageNumber(int pageNumber) {this.pageNumber = pageNumber;}
	public Page<WechatUsers> findPageList(WechatUsers wechatUsers) {
		WhereAndParas wp = getWhereAndParas(wechatUsers);
		return dao.paginate(wechatUsers.getPageNumber(),wechatUsers.getPageSize(),"select * ","from"+ WechatUsers.TABLE + "where 1=1 " +wp.getWhere(),wp.getParas());
	}
	public static final String TABLE = " t_wechat_users ";
	public WhereAndParas getWhereAndParas(WechatUsers wechatUsers){
		StringBuffer sql = new StringBuffer();
		List<Object> list = new ArrayList<Object>();
		WhereAndParas wap = new WhereAndParas();
		if(wechatUsers.getId() != null && wechatUsers.getId() > 0){
			sql.append(" and id = ?");
			list.add(wechatUsers.getId());
		}
		if(StringUtils.isNotEmpty(wechatUsers.getUnionid())){
			sql.append(" and unionid like ?");
			list.add("%"+wechatUsers.getUnionid()+"%");
		}
		if(StringUtils.isNotEmpty(wechatUsers.getOpenid())){
			sql.append(" and openid like ?");
			list.add("%"+wechatUsers.getOpenid()+"%");
		}
		if(StringUtils.isNotEmpty(wechatUsers.getNickname())){
			sql.append(" and nickname like ?");
			list.add("%"+wechatUsers.getNickname()+"%");
		}
		if(StringUtils.isNotEmpty(wechatUsers.getCity())){
			sql.append(" and city like ?");
			list.add("%"+wechatUsers.getCity()+"%");
		}
		if(StringUtils.isNotEmpty(wechatUsers.getCountry())){
			sql.append(" and country like ?");
			list.add("%"+wechatUsers.getCountry()+"%");
		}
		if(StringUtils.isNotEmpty(wechatUsers.getProvince())){
			sql.append(" and province like ?");
			list.add("%"+wechatUsers.getProvince()+"%");
		}
		if(StringUtils.isNotEmpty(wechatUsers.getHeadimgurl())){
			sql.append(" and headimgurl like ?");
			list.add("%"+wechatUsers.getHeadimgurl()+"%");
		}
		if(wechatUsers.getTSid() != null && wechatUsers.getTSid() > 0){
			sql.append(" and t_sid = ?");
			list.add(wechatUsers.getTSid());
		}
		if(wechatUsers.getTCid() != null && wechatUsers.getTCid() > 0){
			sql.append(" and t_cid = ?");
			list.add(wechatUsers.getTCid());
		}
		if(wechatUsers.getVersion() != null && wechatUsers.getVersion() > 0){
			sql.append(" and version = ?");
			list.add(wechatUsers.getVersion());
		}
		if(StringUtils.isNotEmpty(wechatUsers.getSexType())){
			sql.append(" and sexType like ?");
			list.add("%"+wechatUsers.getSexType()+"%");
		}
		if(wechatUsers.getGroupId() != null && wechatUsers.getGroupId() > 0){
			sql.append(" and group_id = ?");
			list.add(wechatUsers.getGroupId());
		}
		wap.setWhere(sql.toString());
		wap.setParas(list.toArray());
		return wap;
	}
}
