package com.xiaoan.wlt.model.base.t;

import com.xiaoan.wlt.common.jfinal.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

import org.apache.commons.lang3.StringUtils;

import com.xiaoan.wlt.common.WhereAndParas;

import java.util.ArrayList;

import java.util.List;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDialingStatus<M extends BaseDialingStatus<M>> extends BaseModel<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public void setVersion(java.lang.Integer version) {
		set("version", version);
	}

	public java.lang.Integer getVersion() {
		return get("version");
	}

	public void setCalled(java.lang.String called) {
		set("called", called);
	}

	public java.lang.String getCalled() {
		return get("called");
	}

	public void setCaller(java.lang.String caller) {
		set("caller", caller);
	}

	public java.lang.String getCaller() {
		return get("caller");
	}

	public void setDescribes(java.lang.String describes) {
		set("describes", describes);
	}

	public java.lang.String getDescribes() {
		return get("describes");
	}

	public void setDialStatus(java.lang.String dialStatus) {
		set("dialStatus", dialStatus);
	}

	public java.lang.String getDialStatus() {
		return get("dialStatus");
	}

	public void setHoldTime(java.lang.Long holdTime) {
		set("holdTime", holdTime);
	}

	public java.lang.Long getHoldTime() {
		return get("holdTime");
	}

	public void setIsCallBack(java.lang.String isCallBack) {
		set("isCallBack", isCallBack);
	}

	public java.lang.String getIsCallBack() {
		return get("isCallBack");
	}

	public void setResult(java.lang.String result) {
		set("result", result);
	}

	public java.lang.String getResult() {
		return get("result");
	}

	public void setSessionId(java.lang.String sessionId) {
		set("sessionId", sessionId);
	}

	public java.lang.String getSessionId() {
		return get("sessionId");
	}

	public void setStartTime(java.util.Date startTime) {
		set("startTime", startTime);
	}

	public java.util.Date getStartTime() {
		return get("startTime");
	}

	public void setCustAcntId(java.lang.Long custAcntId) {
		set("custAcntId", custAcntId);
	}

	public java.lang.Long getCustAcntId() {
		return get("custAcntId");
	}

	public void setIsStatusCallBack(java.lang.String isStatusCallBack) {
		set("isStatusCallBack", isStatusCallBack);
	}

	public java.lang.String getIsStatusCallBack() {
		return get("isStatusCallBack");
	}

	public static final String TABLE = " t_dialing_status ";
	public WhereAndParas getWhereAndParas(BaseDialingStatus dialingStatus){
		StringBuffer sql = new StringBuffer();
		List<Object> list = new ArrayList<Object>();
		WhereAndParas wap = new WhereAndParas();
		if(dialingStatus.getId() != null && dialingStatus.getId() > 0){
			sql.append(" and o.id = ?");
			list.add(dialingStatus.getId());
		}
		if(dialingStatus.getVersion() != null && dialingStatus.getVersion() > 0){
			sql.append(" and o.version = ?");
			list.add(dialingStatus.getVersion());
		}
		if(StringUtils.isNotEmpty(dialingStatus.getCalled())){
			sql.append(" and o.called like ?");
			list.add("%"+dialingStatus.getCalled()+"%");
		}
		if(StringUtils.isNotEmpty(dialingStatus.getCaller())){
			sql.append(" and o.caller like ?");
			list.add("%"+dialingStatus.getCaller()+"%");
		}
		if(StringUtils.isNotEmpty(dialingStatus.getDescribes())){
			sql.append(" and o.describes like ?");
			list.add("%"+dialingStatus.getDescribes()+"%");
		}
		if(StringUtils.isNotEmpty(dialingStatus.getDialStatus())){
			sql.append(" and o.dialStatus like ?");
			list.add("%"+dialingStatus.getDialStatus()+"%");
		}
		if(dialingStatus.getHoldTime() != null && dialingStatus.getHoldTime() > 0){
			sql.append(" and o.holdTime = ?");
			list.add(dialingStatus.getHoldTime());
		}
		if(StringUtils.isNotEmpty(dialingStatus.getIsCallBack())){
			sql.append(" and o.isCallBack like ?");
			list.add("%"+dialingStatus.getIsCallBack()+"%");
		}
		if(StringUtils.isNotEmpty(dialingStatus.getResult())){
			sql.append(" and o.result like ?");
			list.add("%"+dialingStatus.getResult()+"%");
		}
		if(StringUtils.isNotEmpty(dialingStatus.getSessionId())){
			sql.append(" and o.sessionId like ?");
			list.add("%"+dialingStatus.getSessionId()+"%");
		}
		if(dialingStatus.getCustAcntId() != null && dialingStatus.getCustAcntId() > 0){
			sql.append(" and o.custAcntId = ?");
			list.add(dialingStatus.getCustAcntId());
		}
		if(StringUtils.isNotEmpty(dialingStatus.getIsStatusCallBack())){
			sql.append(" and o.isStatusCallBack like ?");
			list.add("%"+dialingStatus.getIsStatusCallBack()+"%");
		}
		wap.setWhere(sql.toString());
		wap.setParas(list.toArray());
		return wap;
	}
}
