package com.xiaoan.wlt.model.base.erp.jxc;

import com.xiaoan.wlt.common.jfinal.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

import org.apache.commons.lang3.StringUtils;

import com.xiaoan.wlt.common.WhereAndParas;

import java.util.ArrayList;

import java.util.List;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDepot<M extends BaseDepot<M>> extends BaseModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setSId(java.lang.Integer sId) {
		set("s_id", sId);
	}

	public java.lang.Integer getSId() {
		return get("s_id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setAddr(java.lang.String addr) {
		set("addr", addr);
	}

	public java.lang.String getAddr() {
		return get("addr");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setRemarks(java.lang.String remarks) {
		set("remarks", remarks);
	}

	public java.lang.String getRemarks() {
		return get("remarks");
	}

	public void setVersion(java.lang.Integer version) {
		set("version", version);
	}

	public java.lang.Integer getVersion() {
		return get("version");
	}

	public static final String TABLE = " erp_jxc_depot ";
	public WhereAndParas getWhereAndParas(BaseDepot depot){
		StringBuffer sql = new StringBuffer();
		List<Object> list = new ArrayList<Object>();
		WhereAndParas wap = new WhereAndParas();
		if(depot.getId() != null && depot.getId() > 0){
			sql.append(" and o.id = ?");
			list.add(depot.getId());
		}
		if(depot.getSId() != null && depot.getSId() > 0){
			sql.append(" and o.s_id = ?");
			list.add(depot.getSId());
		}
		if(StringUtils.isNotEmpty(depot.getName())){
			sql.append(" and o.name like ?");
			list.add("%"+depot.getName()+"%");
		}
		if(StringUtils.isNotEmpty(depot.getAddr())){
			sql.append(" and o.addr like ?");
			list.add("%"+depot.getAddr()+"%");
		}
		if(StringUtils.isNotEmpty(depot.getRemarks())){
			sql.append(" and o.remarks like ?");
			list.add("%"+depot.getRemarks()+"%");
		}
		if(depot.getVersion() != null && depot.getVersion() > 0){
			sql.append(" and o.version = ?");
			list.add(depot.getVersion());
		}
		wap.setWhere(sql.toString());
		wap.setParas(list.toArray());
		return wap;
	}
}
