package com.xiaoan.wlt.model.base.erp.jxc;

import com.xiaoan.wlt.common.jfinal.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

import org.apache.commons.lang3.StringUtils;

import com.xiaoan.wlt.common.WhereAndParas;

import java.util.ArrayList;

import java.util.List;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBeginStock<M extends BaseBeginStock<M>> extends BaseModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setSId(java.lang.Integer sId) {
		set("s_id", sId);
	}

	public java.lang.Integer getSId() {
		return get("s_id");
	}

	public void setVersion(java.lang.Integer version) {
		set("version", version);
	}

	public java.lang.Integer getVersion() {
		return get("version");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setNum(java.math.BigDecimal num) {
		set("num", num);
	}

	public java.math.BigDecimal getNum() {
		return get("num");
	}

	public void setPriceCost(java.math.BigDecimal priceCost) {
		set("price_cost", priceCost);
	}

	public java.math.BigDecimal getPriceCost() {
		return get("price_cost");
	}

	public void setPriceTotal(java.math.BigDecimal priceTotal) {
		set("price_total", priceTotal);
	}

	public java.math.BigDecimal getPriceTotal() {
		return get("price_total");
	}

	public void setPId(java.lang.Integer pId) {
		set("p_id", pId);
	}

	public java.lang.Integer getPId() {
		return get("p_id");
	}

	public void setRemarks(java.lang.String remarks) {
		set("remarks", remarks);
	}

	public java.lang.String getRemarks() {
		return get("remarks");
	}

	public static final String TABLE = " erp_jxc_begin_stock ";
	public WhereAndParas getWhereAndParas(BaseBeginStock beginStock){
		StringBuffer sql = new StringBuffer();
		List<Object> list = new ArrayList<Object>();
		WhereAndParas wap = new WhereAndParas();
		if(beginStock.getId() != null && beginStock.getId() > 0){
			sql.append(" and o.id = ?");
			list.add(beginStock.getId());
		}
		if(beginStock.getSId() != null && beginStock.getSId() > 0){
			sql.append(" and o.s_id = ?");
			list.add(beginStock.getSId());
		}
		if(beginStock.getVersion() != null && beginStock.getVersion() > 0){
			sql.append(" and o.version = ?");
			list.add(beginStock.getVersion());
		}
		if(beginStock.getPId() != null && beginStock.getPId() > 0){
			sql.append(" and o.p_id = ?");
			list.add(beginStock.getPId());
		}
		if(StringUtils.isNotEmpty(beginStock.getRemarks())){
			sql.append(" and o.remarks like ?");
			list.add("%"+beginStock.getRemarks()+"%");
		}
		wap.setWhere(sql.toString());
		wap.setParas(list.toArray());
		return wap;
	}
}
