package com.xiaoan.wlt.model.base.erp.jxc;

import com.xiaoan.wlt.common.jfinal.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

import org.apache.commons.lang3.StringUtils;

import com.xiaoan.wlt.common.WhereAndParas;

import java.util.ArrayList;

import java.util.List;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCustomer<M extends BaseCustomer<M>> extends BaseModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setSId(java.lang.Integer sId) {
		set("s_id", sId);
	}

	public java.lang.Integer getSId() {
		return get("s_id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}

	public java.lang.String getMobile() {
		return get("mobile");
	}

	public void setAmount(java.lang.String amount) {
		set("amount", amount);
	}

	public java.lang.String getAmount() {
		return get("amount");
	}

	public void setState(java.lang.String state) {
		set("state", state);
	}

	public java.lang.String getState() {
		return get("state");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setRemarks(java.lang.String remarks) {
		set("remarks", remarks);
	}

	public java.lang.String getRemarks() {
		return get("remarks");
	}

	public void setVersion(java.lang.Integer version) {
		set("version", version);
	}

	public java.lang.Integer getVersion() {
		return get("version");
	}

	public static final String TABLE = " erp_jxc_customer ";
	public WhereAndParas getWhereAndParas(BaseCustomer customer){
		StringBuffer sql = new StringBuffer();
		List<Object> list = new ArrayList<Object>();
		WhereAndParas wap = new WhereAndParas();
		if(customer.getId() != null && customer.getId() > 0){
			sql.append(" and o.id = ?");
			list.add(customer.getId());
		}
		if(customer.getSId() != null && customer.getSId() > 0){
			sql.append(" and o.s_id = ?");
			list.add(customer.getSId());
		}
		if(StringUtils.isNotEmpty(customer.getName())){
			sql.append(" and o.name like ?");
			list.add("%"+customer.getName()+"%");
		}
		if(StringUtils.isNotEmpty(customer.getMobile())){
			sql.append(" and o.mobile like ?");
			list.add("%"+customer.getMobile()+"%");
		}
		if(StringUtils.isNotEmpty(customer.getAmount())){
			sql.append(" and o.amount like ?");
			list.add("%"+customer.getAmount()+"%");
		}
		if(StringUtils.isNotEmpty(customer.getState())){
			sql.append(" and o.state like ?");
			list.add("%"+customer.getState()+"%");
		}
		if(StringUtils.isNotEmpty(customer.getRemarks())){
			sql.append(" and o.remarks like ?");
			list.add("%"+customer.getRemarks()+"%");
		}
		if(customer.getVersion() != null && customer.getVersion() > 0){
			sql.append(" and o.version = ?");
			list.add(customer.getVersion());
		}
		wap.setWhere(sql.toString());
		wap.setParas(list.toArray());
		return wap;
	}
}
