package com.xiaoan.wlt.model.base.erp.jxc;

import com.xiaoan.wlt.common.jfinal.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

import org.apache.commons.lang3.StringUtils;

import com.xiaoan.wlt.common.WhereAndParas;

import java.util.ArrayList;

import java.util.List;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStockList<M extends BaseStockList<M>> extends BaseModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setSId(java.lang.Integer sId) {
		set("s_id", sId);
	}

	public java.lang.Integer getSId() {
		return get("s_id");
	}

	public void setName(java.lang.String Name) {
		set("Name", Name);
	}

	public java.lang.String getName() {
		return get("Name");
	}

	public void setDepotId(java.lang.Integer depotId) {
		set("depot_id", depotId);
	}

	public java.lang.Integer getDepotId() {
		return get("depot_id");
	}

	public void setProductId(java.lang.Integer productId) {
		set("product_id", productId);
	}

	public java.lang.Integer getProductId() {
		return get("product_id");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}

	public java.lang.String getType() {
		return get("type");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUser(java.lang.String user) {
		set("user", user);
	}

	public java.lang.String getUser() {
		return get("user");
	}

	public void setNum(java.lang.Double num) {
		set("num", num);
	}

	public java.lang.Double getNum() {
		return get("num");
	}

	public void setVersion(java.lang.Integer version) {
		set("version", version);
	}

	public java.lang.Integer getVersion() {
		return get("version");
	}

	public void setRemarks(java.lang.String remarks) {
		set("remarks", remarks);
	}

	public java.lang.String getRemarks() {
		return get("remarks");
	}

	public void setOrderId(java.lang.Integer orderId) {
		set("order_id", orderId);
	}

	public java.lang.Integer getOrderId() {
		return get("order_id");
	}

	public static final String TABLE = " erp_jxc_stock_list ";
	public WhereAndParas getWhereAndParas(BaseStockList stockList){
		StringBuffer sql = new StringBuffer();
		List<Object> list = new ArrayList<Object>();
		WhereAndParas wap = new WhereAndParas();
		if(stockList.getId() != null && stockList.getId() > 0){
			sql.append(" and o.id = ?");
			list.add(stockList.getId());
		}
		if(stockList.getSId() != null && stockList.getSId() > 0){
			sql.append(" and o.s_id = ?");
			list.add(stockList.getSId());
		}
		if(StringUtils.isNotEmpty(stockList.getName())){
			sql.append(" and o.Name like ?");
			list.add("%"+stockList.getName()+"%");
		}
		if(stockList.getDepotId() != null && stockList.getDepotId() > 0){
			sql.append(" and o.depot_id = ?");
			list.add(stockList.getDepotId());
		}
		if(stockList.getProductId() != null && stockList.getProductId() > 0){
			sql.append(" and o.product_id = ?");
			list.add(stockList.getProductId());
		}
		if(StringUtils.isNotEmpty(stockList.getType())){
			sql.append(" and o.type like ?");
			list.add("%"+stockList.getType()+"%");
		}
		if(StringUtils.isNotEmpty(stockList.getUser())){
			sql.append(" and o.user like ?");
			list.add("%"+stockList.getUser()+"%");
		}
		if(stockList.getNum() != null && stockList.getNum() > 0){
			sql.append(" and o.num = ?");
			list.add(stockList.getNum());
		}
		if(stockList.getVersion() != null && stockList.getVersion() > 0){
			sql.append(" and o.version = ?");
			list.add(stockList.getVersion());
		}
		if(StringUtils.isNotEmpty(stockList.getRemarks())){
			sql.append(" and o.remarks like ?");
			list.add("%"+stockList.getRemarks()+"%");
		}
		if(stockList.getOrderId() != null && stockList.getOrderId() > 0){
			sql.append(" and o.order_id = ?");
			list.add(stockList.getOrderId());
		}
		wap.setWhere(sql.toString());
		wap.setParas(list.toArray());
		return wap;
	}
}
