package com.xiaoan.wlt.model.base.erp.jxc;

import com.xiaoan.wlt.common.jfinal.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

import org.apache.commons.lang3.StringUtils;

import com.xiaoan.wlt.common.WhereAndParas;

import java.util.ArrayList;

import java.util.List;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDict<M extends BaseDict<M>> extends BaseModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setSId(java.lang.Integer sId) {
		set("s_id", sId);
	}

	public java.lang.Integer getSId() {
		return get("s_id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setBak(java.lang.String bak) {
		set("bak", bak);
	}

	public java.lang.String getBak() {
		return get("bak");
	}

	public void setRemarks(java.lang.String remarks) {
		set("remarks", remarks);
	}

	public java.lang.String getRemarks() {
		return get("remarks");
	}

	public void setVersion(java.lang.Integer version) {
		set("version", version);
	}

	public java.lang.Integer getVersion() {
		return get("version");
	}

	public static final String TABLE = " erp_jxc_dict ";
	public WhereAndParas getWhereAndParas(BaseDict dict){
		StringBuffer sql = new StringBuffer();
		List<Object> list = new ArrayList<Object>();
		WhereAndParas wap = new WhereAndParas();
		if(dict.getId() != null && dict.getId() > 0){
			sql.append(" and o.id = ?");
			list.add(dict.getId());
		}
		if(dict.getSId() != null && dict.getSId() > 0){
			sql.append(" and o.s_id = ?");
			list.add(dict.getSId());
		}
		if(StringUtils.isNotEmpty(dict.getName())){
			sql.append(" and o.name like ?");
			list.add("%"+dict.getName()+"%");
		}
		if(StringUtils.isNotEmpty(dict.getBak())){
			sql.append(" and o.bak like ?");
			list.add("%"+dict.getBak()+"%");
		}
		if(StringUtils.isNotEmpty(dict.getRemarks())){
			sql.append(" and o.remarks like ?");
			list.add("%"+dict.getRemarks()+"%");
		}
		if(dict.getVersion() != null && dict.getVersion() > 0){
			sql.append(" and o.version = ?");
			list.add(dict.getVersion());
		}
		wap.setWhere(sql.toString());
		wap.setParas(list.toArray());
		return wap;
	}
}
