package com.xiaoan.wlt.model.erp.jxc;

import org.apache.commons.lang3.StringUtils;

import com.xiaoan.wlt.common.WhereAndParas;

import java.util.ArrayList;

import java.util.List;

import com.jfinal.plugin.activerecord.Page;

import com.xiaoan.wlt.model.base.erp.jxc.BaseIntoList;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IntoList extends BaseIntoList<IntoList> {
	public static final IntoList dao = new IntoList();
	private int pageNumber = 1;
	private int pageSize = 15;
	public int getPageSize() {return pageSize;}
	public void setPageSize(int pageSize) {this.pageSize = pageSize;}
	public int getPageNumber() {return pageNumber;}
	public void setPageNumber(int pageNumber) {this.pageNumber = pageNumber;}
	public Page<IntoList> findPageList(IntoList intoList) {
		WhereAndParas wp = getWhereAndParas(intoList);
		return dao.paginate(intoList.getPageNumber(),intoList.getPageSize(),"select * ","from"+ IntoList.TABLE + "where 1=1 " +wp.getWhere(),wp.getParas());
	}
	public static final String TABLE = " erp_jxc_into_list ";
	public WhereAndParas getWhereAndParas(IntoList intoList){
		StringBuffer sql = new StringBuffer();
		List<Object> list = new ArrayList<Object>();
		WhereAndParas wap = new WhereAndParas();
		if(intoList.getId() != null && intoList.getId() > 0){
			sql.append(" and id = ?");
			list.add(intoList.getId());
		}
		if(intoList.getIntoId() != null && intoList.getIntoId() > 0){
			sql.append(" and into_id = ?");
			list.add(intoList.getIntoId());
		}
		if(intoList.getDepotId() != null && intoList.getDepotId() > 0){
			sql.append(" and depot_id = ?");
			list.add(intoList.getDepotId());
		}
		if(intoList.getProductId() != null && intoList.getProductId() > 0){
			sql.append(" and product_id = ?");
			list.add(intoList.getProductId());
		}
		if(intoList.getNum() != null && intoList.getNum() > 0){
			sql.append(" and num = ?");
			list.add(intoList.getNum());
		}
		if(StringUtils.isNotEmpty(intoList.getUnit())){
			sql.append(" and unit like ?");
			list.add("%"+intoList.getUnit()+"%");
		}
		if(intoList.getPriceTotal() != null && intoList.getPriceTotal() > 0){
			sql.append(" and price_total = ?");
			list.add(intoList.getPriceTotal());
		}
		if(intoList.getPriceInto() != null && intoList.getPriceInto() > 0){
			sql.append(" and price_into = ?");
			list.add(intoList.getPriceInto());
		}
		if(intoList.getVersion() != null && intoList.getVersion() > 0){
			sql.append(" and version = ?");
			list.add(intoList.getVersion());
		}
		wap.setWhere(sql.toString());
		wap.setParas(list.toArray());
		return wap;
	}
	public List<IntoList> findByIntoId(Integer intoId) {
		if(intoId == null) return null;
		String sql = "select * from erp_jxc_into_list where into_id = ?";
		return dao.find(sql, intoId);
	}
	
	public List<IntoList> findInfoByIntoId(Integer intoId) {
		if(intoId == null) return null;
		String sql = "select o.*,p.code as pcode,p.name as pname,p.id as pid "
				+ "from erp_jxc_into_list o "
				+ "LEFT JOIN erp_jxc_product p ON o.product_id = p.id "
				+ "WHERE o.into_id = ?";
		return dao.find(sql, intoId);
	}
}
