package com.xiaoan.wlt.model.base.t;

import com.xiaoan.wlt.common.jfinal.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

import org.apache.commons.lang3.StringUtils;

import com.xiaoan.wlt.common.WhereAndParas;

import java.util.ArrayList;

import java.util.List;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStatSaleMonthTarget<M extends BaseStatSaleMonthTarget<M>> extends BaseModel<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public void setVersion(java.lang.Integer version) {
		set("version", version);
	}

	public java.lang.Integer getVersion() {
		return get("version");
	}

	public void setMonths(java.lang.String months) {
		set("months", months);
	}

	public java.lang.String getMonths() {
		return get("months");
	}

	public void setSalesId(java.lang.Long salesId) {
		set("salesId", salesId);
	}

	public java.lang.Long getSalesId() {
		return get("salesId");
	}

	public void setScode(java.lang.String scode) {
		set("scode", scode);
	}

	public java.lang.String getScode() {
		return get("scode");
	}

	public void setTargetType(java.lang.String targetType) {
		set("targetType", targetType);
	}

	public java.lang.String getTargetType() {
		return get("targetType");
	}

	public void setTargetValue(java.lang.String targetValue) {
		set("targetValue", targetValue);
	}

	public java.lang.String getTargetValue() {
		return get("targetValue");
	}

	public void setCommNum(java.lang.String commNum) {
		set("commNum", commNum);
	}

	public java.lang.String getCommNum() {
		return get("commNum");
	}

	public static final String TABLE = " t_stat_sale_month_target ";
	public WhereAndParas getWhereAndParas(BaseStatSaleMonthTarget statSaleMonthTarget){
		StringBuffer sql = new StringBuffer();
		List<Object> list = new ArrayList<Object>();
		WhereAndParas wap = new WhereAndParas();
		if(statSaleMonthTarget.getId() != null && statSaleMonthTarget.getId() > 0){
			sql.append(" and o.id = ?");
			list.add(statSaleMonthTarget.getId());
		}
		if(statSaleMonthTarget.getVersion() != null && statSaleMonthTarget.getVersion() > 0){
			sql.append(" and o.version = ?");
			list.add(statSaleMonthTarget.getVersion());
		}
		if(StringUtils.isNotEmpty(statSaleMonthTarget.getMonths())){
			sql.append(" and o.months like ?");
			list.add("%"+statSaleMonthTarget.getMonths()+"%");
		}
		if(statSaleMonthTarget.getSalesId() != null && statSaleMonthTarget.getSalesId() > 0){
			sql.append(" and o.salesId = ?");
			list.add(statSaleMonthTarget.getSalesId());
		}
		if(StringUtils.isNotEmpty(statSaleMonthTarget.getScode())){
			sql.append(" and o.scode like ?");
			list.add("%"+statSaleMonthTarget.getScode()+"%");
		}
		if(StringUtils.isNotEmpty(statSaleMonthTarget.getTargetType())){
			sql.append(" and o.targetType like ?");
			list.add("%"+statSaleMonthTarget.getTargetType()+"%");
		}
		if(StringUtils.isNotEmpty(statSaleMonthTarget.getTargetValue())){
			sql.append(" and o.targetValue like ?");
			list.add("%"+statSaleMonthTarget.getTargetValue()+"%");
		}
		if(StringUtils.isNotEmpty(statSaleMonthTarget.getCommNum())){
			sql.append(" and o.commNum like ?");
			list.add("%"+statSaleMonthTarget.getCommNum()+"%");
		}
		wap.setWhere(sql.toString());
		wap.setParas(list.toArray());
		return wap;
	}
}
