package com.xiaoan.wlt.model.base.t;

import com.xiaoan.wlt.common.jfinal.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

import org.apache.commons.lang3.StringUtils;

import com.xiaoan.wlt.common.WhereAndParas;

import java.util.ArrayList;

import java.util.List;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWechatUsers<M extends BaseWechatUsers<M>> extends BaseModel<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setUnionid(java.lang.String unionid) {
		set("unionid", unionid);
	}

	public java.lang.String getUnionid() {
		return get("unionid");
	}

	public void setOpenid(java.lang.String openid) {
		set("openid", openid);
	}

	public java.lang.String getOpenid() {
		return get("openid");
	}

	public void setNickname(java.lang.String nickname) {
		set("nickname", nickname);
	}

	public java.lang.String getNickname() {
		return get("nickname");
	}

	public void setCity(java.lang.String city) {
		set("city", city);
	}

	public java.lang.String getCity() {
		return get("city");
	}

	public void setCountry(java.lang.String country) {
		set("country", country);
	}

	public java.lang.String getCountry() {
		return get("country");
	}

	public void setProvince(java.lang.String province) {
		set("province", province);
	}

	public java.lang.String getProvince() {
		return get("province");
	}

	public void setHeadimgurl(java.lang.String headimgurl) {
		set("headimgurl", headimgurl);
	}

	public java.lang.String getHeadimgurl() {
		return get("headimgurl");
	}

	public void setTSid(java.lang.Long tSid) {
		set("t_sid", tSid);
	}

	public java.lang.Long getTSid() {
		return get("t_sid");
	}

	public void setTCid(java.lang.Long tCid) {
		set("t_cid", tCid);
	}

	public java.lang.Long getTCid() {
		return get("t_cid");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public void setVersion(java.lang.Long version) {
		set("version", version);
	}

	public java.lang.Long getVersion() {
		return get("version");
	}

	public void setSexType(java.lang.String sexType) {
		set("sexType", sexType);
	}

	public java.lang.String getSexType() {
		return get("sexType");
	}

	public void setGroupId(java.lang.Integer groupId) {
		set("group_id", groupId);
	}

	public java.lang.Integer getGroupId() {
		return get("group_id");
	}

	public static final String TABLE = " t_wechat_users ";
	public WhereAndParas getWhereAndParas(BaseWechatUsers wechatUsers){
		StringBuffer sql = new StringBuffer();
		List<Object> list = new ArrayList<Object>();
		WhereAndParas wap = new WhereAndParas();
		if(wechatUsers.getId() != null && wechatUsers.getId() > 0){
			sql.append(" and o.id = ?");
			list.add(wechatUsers.getId());
		}
		if(StringUtils.isNotEmpty(wechatUsers.getUnionid())){
			sql.append(" and o.unionid like ?");
			list.add("%"+wechatUsers.getUnionid()+"%");
		}
		if(StringUtils.isNotEmpty(wechatUsers.getOpenid())){
			sql.append(" and o.openid like ?");
			list.add("%"+wechatUsers.getOpenid()+"%");
		}
		if(StringUtils.isNotEmpty(wechatUsers.getNickname())){
			sql.append(" and o.nickname like ?");
			list.add("%"+wechatUsers.getNickname()+"%");
		}
		if(StringUtils.isNotEmpty(wechatUsers.getCity())){
			sql.append(" and o.city like ?");
			list.add("%"+wechatUsers.getCity()+"%");
		}
		if(StringUtils.isNotEmpty(wechatUsers.getCountry())){
			sql.append(" and o.country like ?");
			list.add("%"+wechatUsers.getCountry()+"%");
		}
		if(StringUtils.isNotEmpty(wechatUsers.getProvince())){
			sql.append(" and o.province like ?");
			list.add("%"+wechatUsers.getProvince()+"%");
		}
		if(StringUtils.isNotEmpty(wechatUsers.getHeadimgurl())){
			sql.append(" and o.headimgurl like ?");
			list.add("%"+wechatUsers.getHeadimgurl()+"%");
		}
		if(wechatUsers.getTSid() != null && wechatUsers.getTSid() > 0){
			sql.append(" and o.t_sid = ?");
			list.add(wechatUsers.getTSid());
		}
		if(wechatUsers.getTCid() != null && wechatUsers.getTCid() > 0){
			sql.append(" and o.t_cid = ?");
			list.add(wechatUsers.getTCid());
		}
		if(wechatUsers.getVersion() != null && wechatUsers.getVersion() > 0){
			sql.append(" and o.version = ?");
			list.add(wechatUsers.getVersion());
		}
		if(StringUtils.isNotEmpty(wechatUsers.getSexType())){
			sql.append(" and o.sexType like ?");
			list.add("%"+wechatUsers.getSexType()+"%");
		}
		if(wechatUsers.getGroupId() != null && wechatUsers.getGroupId() > 0){
			sql.append(" and o.group_id = ?");
			list.add(wechatUsers.getGroupId());
		}
		wap.setWhere(sql.toString());
		wap.setParas(list.toArray());
		return wap;
	}
}
