package com.xiaoan.wlt.model.zyk;

import com.xiaoan.wlt.model.base.zyk.BaseShopsResource;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ShopsResource extends BaseShopsResource<ShopsResource> {
	public static final ShopsResource dao = new ShopsResource();

	public Category getCat() {
		return Category.dao.findById(get("category"));
	}
}
