package com.xiaoan.wlt.model.base.erp.jxc;

import com.xiaoan.wlt.common.jfinal.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

import org.apache.commons.lang3.StringUtils;

import com.xiaoan.wlt.common.WhereAndParas;

import java.util.ArrayList;

import java.util.List;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOutIntoList<M extends BaseOutIntoList<M>> extends BaseModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setSId(java.lang.Integer sId) {
		set("s_id", sId);
	}

	public java.lang.Integer getSId() {
		return get("s_id");
	}

	public void setProductId(java.lang.Integer productId) {
		set("product_id", productId);
	}

	public java.lang.Integer getProductId() {
		return get("product_id");
	}

	public void setIntoListId(java.lang.Integer intoListId) {
		set("into_list_id", intoListId);
	}

	public java.lang.Integer getIntoListId() {
		return get("into_list_id");
	}

	public void setIntoPrice(java.lang.Double intoPrice) {
		set("into_price", intoPrice);
	}

	public java.lang.Double getIntoPrice() {
		return get("into_price");
	}

	public void setNum(java.lang.Double num) {
		set("num", num);
	}

	public java.lang.Double getNum() {
		return get("num");
	}

	public void setDifference(java.lang.Double difference) {
		set("difference", difference);
	}

	public java.lang.Double getDifference() {
		return get("difference");
	}

	public void setOutListId(java.lang.Integer outListId) {
		set("out_list_id", outListId);
	}

	public java.lang.Integer getOutListId() {
		return get("out_list_id");
	}

	public void setOutPrice(java.lang.Double outPrice) {
		set("out_price", outPrice);
	}

	public java.lang.Double getOutPrice() {
		return get("out_price");
	}

	public void setRemarks(java.lang.String remarks) {
		set("remarks", remarks);
	}

	public java.lang.String getRemarks() {
		return get("remarks");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public static final String TABLE = " erp_jxc_out_into_list ";
	public WhereAndParas getWhereAndParas(BaseOutIntoList outIntoList){
		StringBuffer sql = new StringBuffer();
		List<Object> list = new ArrayList<Object>();
		WhereAndParas wap = new WhereAndParas();
		if(outIntoList.getId() != null && outIntoList.getId() > 0){
			sql.append(" and o.id = ?");
			list.add(outIntoList.getId());
		}
		if(outIntoList.getSId() != null && outIntoList.getSId() > 0){
			sql.append(" and o.s_id = ?");
			list.add(outIntoList.getSId());
		}
		if(outIntoList.getProductId() != null && outIntoList.getProductId() > 0){
			sql.append(" and o.product_id = ?");
			list.add(outIntoList.getProductId());
		}
		if(outIntoList.getIntoListId() != null && outIntoList.getIntoListId() > 0){
			sql.append(" and o.into_list_id = ?");
			list.add(outIntoList.getIntoListId());
		}
		if(outIntoList.getIntoPrice() != null && outIntoList.getIntoPrice() > 0){
			sql.append(" and o.into_price = ?");
			list.add(outIntoList.getIntoPrice());
		}
		if(outIntoList.getNum() != null && outIntoList.getNum() > 0){
			sql.append(" and o.num = ?");
			list.add(outIntoList.getNum());
		}
		if(outIntoList.getDifference() != null && outIntoList.getDifference() > 0){
			sql.append(" and o.difference = ?");
			list.add(outIntoList.getDifference());
		}
		if(outIntoList.getOutListId() != null && outIntoList.getOutListId() > 0){
			sql.append(" and o.out_list_id = ?");
			list.add(outIntoList.getOutListId());
		}
		if(outIntoList.getOutPrice() != null && outIntoList.getOutPrice() > 0){
			sql.append(" and o.out_price = ?");
			list.add(outIntoList.getOutPrice());
		}
		if(StringUtils.isNotEmpty(outIntoList.getRemarks())){
			sql.append(" and o.remarks like ?");
			list.add("%"+outIntoList.getRemarks()+"%");
		}
		wap.setWhere(sql.toString());
		wap.setParas(list.toArray());
		return wap;
	}
}
