package com.xiaoan.wlt.model.erp.jxc;

import org.apache.commons.lang3.StringUtils;

import com.xiaoan.wlt.common.WhereAndParas;

import java.util.ArrayList;

import java.util.List;

import com.jfinal.plugin.activerecord.Page;

import com.xiaoan.wlt.model.base.erp.jxc.BaseCustomer;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Customer extends BaseCustomer<Customer> {
	public static final Customer dao = new Customer();
	private int pageNumber = 1;
	private int pageSize = 15;
	public int getPageSize() {return pageSize;}
	public void setPageSize(int pageSize) {this.pageSize = pageSize;}
	public int getPageNumber() {return pageNumber;}
	public void setPageNumber(int pageNumber) {this.pageNumber = pageNumber;}
	public Page<Customer> findPageList(Customer customer) {
		WhereAndParas wp = getWhereAndParas(customer);
		return dao.paginate(customer.getPageNumber(),customer.getPageSize(),"select * ","from"+ Customer.TABLE + "where 1=1 " +wp.getWhere(),wp.getParas());
	}
	public static final String TABLE = " erp_jxc_customer ";
	public WhereAndParas getWhereAndParas(Customer customer){
		StringBuffer sql = new StringBuffer();
		List<Object> list = new ArrayList<Object>();
		WhereAndParas wap = new WhereAndParas();
		if(customer.getId() != null && customer.getId() > 0){
			sql.append(" and id = ?");
			list.add(customer.getId());
		}
		if(customer.getSId() != null && customer.getSId() > 0){
			sql.append(" and s_id = ?");
			list.add(customer.getSId());
		}
		if(StringUtils.isNotEmpty(customer.getName())){
			sql.append(" and name like ?");
			list.add("%"+customer.getName()+"%");
		}
		if(StringUtils.isNotEmpty(customer.getMobile())){
			sql.append(" and mobile like ?");
			list.add("%"+customer.getMobile()+"%");
		}
		if(StringUtils.isNotEmpty(customer.getAmount())){
			sql.append(" and amount like ?");
			list.add("%"+customer.getAmount()+"%");
		}
		if(StringUtils.isNotEmpty(customer.getState())){
			sql.append(" and state like ?");
			list.add("%"+customer.getState()+"%");
		}
		if(StringUtils.isNotEmpty(customer.getRemarks())){
			sql.append(" and remarks like ?");
			list.add("%"+customer.getRemarks()+"%");
		}
		if(customer.getVersion() != null && customer.getVersion() > 0){
			sql.append(" and version = ?");
			list.add(customer.getVersion());
		}
		wap.setWhere(sql.toString());
		wap.setParas(list.toArray());
		return wap;
	}
}
