package com.xiaoan.wlt.model.erp.jxc;

import org.apache.commons.lang3.StringUtils;

import com.xiaoan.wlt.common.WhereAndParas;

import java.util.ArrayList;

import java.util.List;

import com.jfinal.plugin.activerecord.Page;

import com.xiaoan.wlt.model.base.erp.jxc.BaseDepot;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Depot extends BaseDepot<Depot> {
	public static final Depot dao = new Depot();
	private int pageNumber = 1;
	private int pageSize = 15;
	public int getPageSize() {return pageSize;}
	public void setPageSize(int pageSize) {this.pageSize = pageSize;}
	public int getPageNumber() {return pageNumber;}
	public void setPageNumber(int pageNumber) {this.pageNumber = pageNumber;}
	public Page<Depot> findPageList(Depot depot) {
		WhereAndParas wp = getWhereAndParas(depot);
		return dao.paginate(depot.getPageNumber(),depot.getPageSize(),"select * ","from"+ Depot.TABLE + "where 1=1 " +wp.getWhere(),wp.getParas());
	}
	public static final String TABLE = " erp_jxc_depot ";
	public WhereAndParas getWhereAndParas(Depot depot){
		StringBuffer sql = new StringBuffer();
		List<Object> list = new ArrayList<Object>();
		WhereAndParas wap = new WhereAndParas();
		if(depot.getId() != null && depot.getId() > 0){
			sql.append(" and id = ?");
			list.add(depot.getId());
		}
		if(depot.getSId() != null && depot.getSId() > 0){
			sql.append(" and s_id = ?");
			list.add(depot.getSId());
		}
		if(StringUtils.isNotEmpty(depot.getName())){
			sql.append(" and name like ?");
			list.add("%"+depot.getName()+"%");
		}
		if(StringUtils.isNotEmpty(depot.getAddr())){
			sql.append(" and addr like ?");
			list.add("%"+depot.getAddr()+"%");
		}
		if(StringUtils.isNotEmpty(depot.getRemarks())){
			sql.append(" and remarks like ?");
			list.add("%"+depot.getRemarks()+"%");
		}
		if(depot.getVersion() != null && depot.getVersion() > 0){
			sql.append(" and version = ?");
			list.add(depot.getVersion());
		}
		wap.setWhere(sql.toString());
		wap.setParas(list.toArray());
		return wap;
	}
}
