package com.xiaoan.wlt.model.erp.jxc;

import org.apache.commons.lang3.StringUtils;

import com.xiaoan.wlt.common.WhereAndParas;

import java.util.ArrayList;

import java.util.List;

import com.jfinal.plugin.activerecord.Page;

import com.xiaoan.wlt.model.base.erp.jxc.BaseDict;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Dict extends BaseDict<Dict> {
	public static final Dict dao = new Dict();
	private int pageNumber = 1;
	private int pageSize = 15;
	public int getPageSize() {return pageSize;}
	public void setPageSize(int pageSize) {this.pageSize = pageSize;}
	public int getPageNumber() {return pageNumber;}
	public void setPageNumber(int pageNumber) {this.pageNumber = pageNumber;}
	public Page<Dict> findPageList(Dict dict) {
		WhereAndParas wp = getWhereAndParas(dict);
		return dao.paginate(dict.getPageNumber(),dict.getPageSize(),"select * ","from"+ Dict.TABLE + "where 1=1 " +wp.getWhere(),wp.getParas());
	}
	public static final String TABLE = " erp_jxc_dict ";
	public WhereAndParas getWhereAndParas(Dict dict){
		StringBuffer sql = new StringBuffer();
		List<Object> list = new ArrayList<Object>();
		WhereAndParas wap = new WhereAndParas();
		if(dict.getId() != null && dict.getId() > 0){
			sql.append(" and id = ?");
			list.add(dict.getId());
		}
		if(dict.getSId() != null && dict.getSId() > 0){
			sql.append(" and s_id = ?");
			list.add(dict.getSId());
		}
		if(StringUtils.isNotEmpty(dict.getName())){
			sql.append(" and name like ?");
			list.add("%"+dict.getName()+"%");
		}
		if(StringUtils.isNotEmpty(dict.getBak())){
			sql.append(" and bak like ?");
			list.add("%"+dict.getBak()+"%");
		}
		if(StringUtils.isNotEmpty(dict.getRemarks())){
			sql.append(" and remarks like ?");
			list.add("%"+dict.getRemarks()+"%");
		}
		if(dict.getVersion() != null && dict.getVersion() > 0){
			sql.append(" and version = ?");
			list.add(dict.getVersion());
		}
		wap.setWhere(sql.toString());
		wap.setParas(list.toArray());
		return wap;
	}
}
