package com.xiaoan.wlt.model.erp.jxc;

import org.apache.commons.lang3.StringUtils;

import com.xiaoan.wlt.common.WhereAndParas;

import java.util.ArrayList;

import java.util.List;

import com.jfinal.plugin.activerecord.Page;

import com.xiaoan.wlt.model.base.erp.jxc.BaseOutList;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OutList extends BaseOutList<OutList> {
	public static final OutList dao = new OutList();
	private int pageNumber = 1;
	private int pageSize = 15;
	public int getPageSize() {return pageSize;}
	public void setPageSize(int pageSize) {this.pageSize = pageSize;}
	public int getPageNumber() {return pageNumber;}
	public void setPageNumber(int pageNumber) {this.pageNumber = pageNumber;}
	public Page<OutList> findPageList(OutList outList) {
		WhereAndParas wp = getWhereAndParas(outList);
		return dao.paginate(outList.getPageNumber(),outList.getPageSize(),"select * ","from"+ OutList.TABLE + "where 1=1 " +wp.getWhere(),wp.getParas());
	}
	public static final String TABLE = " erp_jxc_out_list ";
	public WhereAndParas getWhereAndParas(OutList outList){
		StringBuffer sql = new StringBuffer();
		List<Object> list = new ArrayList<Object>();
		WhereAndParas wap = new WhereAndParas();
		if(outList.getId() != null && outList.getId() > 0){
			sql.append(" and id = ?");
			list.add(outList.getId());
		}
		if(outList.getOutId() != null && outList.getOutId() > 0){
			sql.append(" and out_id = ?");
			list.add(outList.getOutId());
		}
		if(outList.getProductId() != null && outList.getProductId() > 0){
			sql.append(" and product_id = ?");
			list.add(outList.getProductId());
		}
		if(outList.getDepotId() != null && outList.getDepotId() > 0){
			sql.append(" and depot_id = ?");
			list.add(outList.getDepotId());
		}
		if(outList.getNum() != null && outList.getNum() > 0){
			sql.append(" and num = ?");
			list.add(outList.getNum());
		}
		if(StringUtils.isNotEmpty(outList.getUnit())){
			sql.append(" and unit like ?");
			list.add("%"+outList.getUnit()+"%");
		}
		if(outList.getPriceTotal() != null && outList.getPriceTotal() > 0){
			sql.append(" and price_total = ?");
			list.add(outList.getPriceTotal());
		}
		if(outList.getPriceOut() != null && outList.getPriceOut() > 0){
			sql.append(" and price_out = ?");
			list.add(outList.getPriceOut());
		}
		if(outList.getVersion() != null && outList.getVersion() > 0){
			sql.append(" and version = ?");
			list.add(outList.getVersion());
		}
		wap.setWhere(sql.toString());
		wap.setParas(list.toArray());
		return wap;
	}
	public List<OutList> findByOutId(Integer id) {
		
		if(id == null) return null;
		String sql = "select * from erp_jxc_out_list where out_id = ?";
		return dao.find(sql, id);
		
	}
	public List<OutList> findInfoByIntoId(Integer id) {
		if(id == null) return null;
		String sql = "select o.*,p.code as pcode,p.name as pname "
				+ "from erp_jxc_out_list o "
				+ "LEFT JOIN erp_jxc_product p ON o.product_id = p.id "
				+ "WHERE o.out_id = ?";
		return dao.find(sql, id);
	}
}
