package com.xiaoan.wlt.model.erp.jxc;

import org.apache.commons.lang3.StringUtils;

import com.xiaoan.wlt.common.WhereAndParas;

import java.util.ArrayList;

import java.util.List;

import com.jfinal.plugin.activerecord.Page;

import com.xiaoan.wlt.model.base.erp.jxc.BaseStockList;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StockList extends BaseStockList<StockList> {
	public static final StockList dao = new StockList();
	private int pageNumber = 1;
	private int pageSize = 15;
	public int getPageSize() {return pageSize;}
	public void setPageSize(int pageSize) {this.pageSize = pageSize;}
	public int getPageNumber() {return pageNumber;}
	public void setPageNumber(int pageNumber) {this.pageNumber = pageNumber;}
	public Page<StockList> findPageList(StockList stockList) {
		WhereAndParas wp = getWhereAndParas(stockList);
		return dao.paginate(stockList.getPageNumber(),stockList.getPageSize(),"select * ","from"+ StockList.TABLE + "where 1=1 " +wp.getWhere(),wp.getParas());
	}
	public static final String TABLE = " erp_jxc_stock_list ";
	public WhereAndParas getWhereAndParas(StockList stockList){
		StringBuffer sql = new StringBuffer();
		List<Object> list = new ArrayList<Object>();
		WhereAndParas wap = new WhereAndParas();
		if(stockList.getId() != null && stockList.getId() > 0){
			sql.append(" and id = ?");
			list.add(stockList.getId());
		}
		if(stockList.getSId() != null && stockList.getSId() > 0){
			sql.append(" and s_id = ?");
			list.add(stockList.getSId());
		}
		if(StringUtils.isNotEmpty(stockList.getName())){
			sql.append(" and Name like ?");
			list.add("%"+stockList.getName()+"%");
		}
		if(stockList.getDepotId() != null && stockList.getDepotId() > 0){
			sql.append(" and depot_id = ?");
			list.add(stockList.getDepotId());
		}
		if(stockList.getProductId() != null && stockList.getProductId() > 0){
			sql.append(" and product_id = ?");
			list.add(stockList.getProductId());
		}
		if(StringUtils.isNotEmpty(stockList.getType())){
			sql.append(" and type like ?");
			list.add("%"+stockList.getType()+"%");
		}
		if(StringUtils.isNotEmpty(stockList.getUser())){
			sql.append(" and user like ?");
			list.add("%"+stockList.getUser()+"%");
		}
		if(stockList.getNum() != null && stockList.getNum() > 0){
			sql.append(" and num = ?");
			list.add(stockList.getNum());
		}
		if(stockList.getVersion() != null && stockList.getVersion() > 0){
			sql.append(" and version = ?");
			list.add(stockList.getVersion());
		}
		wap.setWhere(sql.toString());
		wap.setParas(list.toArray());
		return wap;
	}
}
