package com.xiaoan.wlt.model.erp.jxc;

import org.apache.commons.lang3.StringUtils;

import com.xiaoan.wlt.common.WhereAndParas;

import java.util.ArrayList;

import java.util.List;

import com.jfinal.plugin.activerecord.Page;

import com.xiaoan.wlt.model.base.erp.jxc.BaseSupplier;
import com.xiaoan.wlt.shiro.UserContext;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Supplier extends BaseSupplier<Supplier> {
	public static final Supplier dao = new Supplier();
	private int pageNumber = 1;
	private int pageSize = 15;
	public int getPageSize() {return pageSize;}
	public void setPageSize(int pageSize) {this.pageSize = pageSize;}
	public int getPageNumber() {return pageNumber;}
	public void setPageNumber(int pageNumber) {this.pageNumber = pageNumber;}
	public Page<Supplier> findPageList(Supplier supplier) {
		WhereAndParas wp = getWhereAndParas(supplier);
		return dao.paginate(supplier.getPageNumber(),supplier.getPageSize(),"select * ","from"+ Supplier.TABLE + "where 1=1 " +wp.getWhere(),wp.getParas());
	}
	public static final String TABLE = " erp_jxc_supplier ";
	public WhereAndParas getWhereAndParas(Supplier supplier){
		StringBuffer sql = new StringBuffer();
		List<Object> list = new ArrayList<Object>();
		WhereAndParas wap = new WhereAndParas();
		if(supplier.getId() != null && supplier.getId() > 0){
			sql.append(" and id = ?");
			list.add(supplier.getId());
		}
		if(supplier.getSId() != null && supplier.getSId() > 0){
			sql.append(" and s_id = ?");
			list.add(supplier.getSId());
		}
		if(StringUtils.isNotEmpty(supplier.getName())){
			sql.append(" and name like ?");
			list.add("%"+supplier.getName()+"%");
		}
		if(StringUtils.isNotEmpty(supplier.getMobile())){
			sql.append(" and mobile like ?");
			list.add("%"+supplier.getMobile()+"%");
		}
		if(StringUtils.isNotEmpty(supplier.getAddr())){
			sql.append(" and addr like ?");
			list.add("%"+supplier.getAddr()+"%");
		}
		if(StringUtils.isNotEmpty(supplier.getAppellation())){
			sql.append(" and appellation like ?");
			list.add("%"+supplier.getAppellation()+"%");
		}
		if(supplier.getAmount() != null && supplier.getAmount() > 0){
			sql.append(" and amount = ?");
			list.add(supplier.getAmount());
		}
		if(StringUtils.isNotEmpty(supplier.getState())){
			sql.append(" and state like ?");
			list.add("%"+supplier.getState()+"%");
		}
		if(StringUtils.isNotEmpty(supplier.getRemarks())){
			sql.append(" and remarks like ?");
			list.add("%"+supplier.getRemarks()+"%");
		}
		if(supplier.getVersion() != null && supplier.getVersion() > 0){
			sql.append(" and version = ?");
			list.add(supplier.getVersion());
		}
		wap.setWhere(sql.toString());
		wap.setParas(list.toArray());
		return wap;
	}
	public List<Supplier> findList() {
		String sql = "select * from erp_jxc_supplier where s_id = ?";
		return dao.find(sql, UserContext.getShopsInfo());
	}
}
