package com.xiaoan.wlt.model.sys;

import java.util.ArrayList;
import java.util.List;

import org.apache.commons.lang3.StringUtils;

import com.jfinal.plugin.activerecord.Page;
import com.xiaoan.wlt.common.WhereAndParas;
import com.xiaoan.wlt.model.base.sys.BaseRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Role extends BaseRole<Role> {
	public static final Role dao = new Role();
	private int pageNumber = 1;
	private int pageSize = 15;
	public int getPageSize() {return pageSize;}
	public void setPageSize(int pageSize) {this.pageSize = pageSize;}
	public int getPageNumber() {return pageNumber;}
	public void setPageNumber(int pageNumber) {this.pageNumber = pageNumber;}
	public Page<Role> findPageList(Role role) {
		WhereAndParas wp = getWhereAndParas(role);
		return dao.paginate(role.getPageNumber(),role.getPageSize(),"select * ","from"+ Role.TABLE + "where 1=1 " +wp.getWhere(),wp.getParas());
	}
	public static final String TABLE = " sys_role ";
	public WhereAndParas getWhereAndParas(Role role){
		StringBuffer sql = new StringBuffer();
		List<Object> list = new ArrayList<Object>();
		WhereAndParas wap = new WhereAndParas();
		if(role.getId() != null && role.getId() > 0){
			sql.append(" and id = ?");
			list.add(role.getId());
		}
		if(role.getVersion() != null && role.getVersion() > 0){
			sql.append(" and version = ?");
			list.add(role.getVersion());
		}
		if(StringUtils.isNotEmpty(role.getRemark())){
			sql.append(" and remark like ?");
			list.add("%"+role.getRemark()+"%");
		}
		if(StringUtils.isNotEmpty(role.getRoleName())){
			sql.append(" and roleName like ?");
			list.add("%"+role.getRoleName()+"%");
		}
		if(StringUtils.isNotEmpty(role.getState())){
			sql.append(" and state like ?");
			list.add("%"+role.getState()+"%");
		}
		wap.setWhere(sql.toString());
		wap.setParas(list.toArray());
		return wap;
	}
	public List<Role> findList() {
		return dao.find("select * from sys_role");
	}
}
