package com.xiaoan.wlt.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("erp_jxc_begin_stock", "id", com.xiaoan.wlt.model.erp.jxc.BeginStock.class);
		arp.addMapping("erp_jxc_category", "id", com.xiaoan.wlt.model.erp.jxc.Category.class);
		arp.addMapping("erp_jxc_customer", "id", com.xiaoan.wlt.model.erp.jxc.Customer.class);
		arp.addMapping("erp_jxc_depot", "id", com.xiaoan.wlt.model.erp.jxc.Depot.class);
		arp.addMapping("erp_jxc_dict", "id", com.xiaoan.wlt.model.erp.jxc.Dict.class);
		arp.addMapping("erp_jxc_into", "id", com.xiaoan.wlt.model.erp.jxc.Into.class);
		arp.addMapping("erp_jxc_into_list", "id", com.xiaoan.wlt.model.erp.jxc.IntoList.class);
		arp.addMapping("erp_jxc_out", "id", com.xiaoan.wlt.model.erp.jxc.Out.class);
		arp.addMapping("erp_jxc_out_into_list", "id", com.xiaoan.wlt.model.erp.jxc.OutIntoList.class);
		arp.addMapping("erp_jxc_out_list", "id", com.xiaoan.wlt.model.erp.jxc.OutList.class);
		arp.addMapping("erp_jxc_product", "id", com.xiaoan.wlt.model.erp.jxc.Product.class);
		arp.addMapping("erp_jxc_shops_info", "id", com.xiaoan.wlt.model.erp.jxc.ShopsInfo.class);
		arp.addMapping("erp_jxc_stock", "id", com.xiaoan.wlt.model.erp.jxc.Stock.class);
		arp.addMapping("erp_jxc_stock_list", "id", com.xiaoan.wlt.model.erp.jxc.StockList.class);
		arp.addMapping("erp_jxc_supplier", "id", com.xiaoan.wlt.model.erp.jxc.Supplier.class);
		arp.addMapping("sys_function", "funcCde", com.xiaoan.wlt.model.sys.Function.class);
		arp.addMapping("sys_log", "id", com.xiaoan.wlt.model.sys.Log.class);
		arp.addMapping("sys_role", "id", com.xiaoan.wlt.model.sys.Role.class);
		arp.addMapping("sys_role_path", "id", com.xiaoan.wlt.model.sys.RolePath.class);
		arp.addMapping("sys_role_perm", "id", com.xiaoan.wlt.model.sys.RolePerm.class);
		arp.addMapping("sys_role_user", "id", com.xiaoan.wlt.model.sys.RoleUser.class);
		arp.addMapping("sys_user", "id", com.xiaoan.wlt.model.sys.User.class);
		arp.addMapping("sys_user_salesman", "id", com.xiaoan.wlt.model.sys.UserSalesman.class);
		arp.addMapping("t_anas_goal", "id", com.xiaoan.wlt.model.t.AnasGoal.class);
		arp.addMapping("t_cust_account", "id", com.xiaoan.wlt.model.t.CustAccount.class);
		arp.addMapping("t_dialing_status", "id", com.xiaoan.wlt.model.t.DialingStatus.class);
		arp.addMapping("t_stat_sale_month_target", "id", com.xiaoan.wlt.model.t.StatSaleMonthTarget.class);
		arp.addMapping("t_stat_sale_tot_month", "id", com.xiaoan.wlt.model.t.StatSaleTotMonth.class);
		arp.addMapping("t_wechat_users", "id", com.xiaoan.wlt.model.t.WechatUsers.class);
		arp.addMapping("zyk_act_log", "id", com.xiaoan.wlt.model.zyk.ActLog.class);
		arp.addMapping("zyk_category", "id", com.xiaoan.wlt.model.zyk.Category.class);
		arp.addMapping("zyk_resource_template", "id", com.xiaoan.wlt.model.zyk.ResourceTemplate.class);
		arp.addMapping("zyk_shops_resource", "id", com.xiaoan.wlt.model.zyk.ShopsResource.class);
	}
}

