package com.xiaoan.wlt.model.erp.jxc;

import com.jfinal.plugin.activerecord.Page;
import com.xiaoan.wlt.common.WhereAndParas;
import com.xiaoan.wlt.model.base.erp.jxc.BaseProduct;
import com.xiaoan.wlt.shiro.UserContext;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Product extends BaseProduct<Product> {
	public static final Product dao = new Product();
	public Page<Product> findPageList(Product product) {
		WhereAndParas wp = getWhereAndParas(product);
		return dao.paginate(product.getPageNumber(),product.getPageSize(),"select * ","from"+ Product.TABLE + " where 1=1 " +wp.getWhere(),wp.getParas());
	}
	public Product findbyCode(String code) {
		String sql = "SELECT * FROM erp_jxc_product where s_id = ? and code = ?";
		try {
			return dao.findFirst(sql,UserContext.getShopsInfo(),code);
		} catch (Exception e) {
			return null;
		}
	}
}
