package com.xiaoan.wlt.model.base.erp.jxc;

import com.xiaoan.wlt.common.jfinal.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

import org.apache.commons.lang3.StringUtils;

import com.xiaoan.wlt.common.WhereAndParas;

import java.util.ArrayList;

import java.util.List;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseIntoList<M extends BaseIntoList<M>> extends BaseModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setIntoId(java.lang.Integer intoId) {
		set("into_id", intoId);
	}

	public java.lang.Integer getIntoId() {
		return get("into_id");
	}

	public void setDepotId(java.lang.Integer depotId) {
		set("depot_id", depotId);
	}

	public java.lang.Integer getDepotId() {
		return get("depot_id");
	}

	public void setProductId(java.lang.Integer productId) {
		set("product_id", productId);
	}

	public java.lang.Integer getProductId() {
		return get("product_id");
	}

	public void setNum(java.lang.Double num) {
		set("num", num);
	}

	public java.lang.Double getNum() {
		return get("num");
	}

	public void setUnit(java.lang.String unit) {
		set("unit", unit);
	}

	public java.lang.String getUnit() {
		return get("unit");
	}

	public void setPriceTotal(java.lang.Double priceTotal) {
		set("price_total", priceTotal);
	}

	public java.lang.Double getPriceTotal() {
		return get("price_total");
	}

	public void setPriceInto(java.lang.Double priceInto) {
		set("price_into", priceInto);
	}

	public java.lang.Double getPriceInto() {
		return get("price_into");
	}

	public void setVersion(java.lang.Integer version) {
		set("version", version);
	}

	public java.lang.Integer getVersion() {
		return get("version");
	}

	public void setState(java.lang.String state) {
		set("state", state);
	}

	public java.lang.String getState() {
		return get("state");
	}

	public void setNumOut(java.lang.Double numOut) {
		set("num_out", numOut);
	}

	public java.lang.Double getNumOut() {
		return get("num_out");
	}

	public static final String TABLE = " erp_jxc_into_list ";
	public WhereAndParas getWhereAndParas(BaseIntoList intoList){
		StringBuffer sql = new StringBuffer();
		List<Object> list = new ArrayList<Object>();
		WhereAndParas wap = new WhereAndParas();
		if(intoList.getId() != null && intoList.getId() > 0){
			sql.append(" and o.id = ?");
			list.add(intoList.getId());
		}
		if(intoList.getIntoId() != null && intoList.getIntoId() > 0){
			sql.append(" and o.into_id = ?");
			list.add(intoList.getIntoId());
		}
		if(intoList.getDepotId() != null && intoList.getDepotId() > 0){
			sql.append(" and o.depot_id = ?");
			list.add(intoList.getDepotId());
		}
		if(intoList.getProductId() != null && intoList.getProductId() > 0){
			sql.append(" and o.product_id = ?");
			list.add(intoList.getProductId());
		}
		if(intoList.getNum() != null && intoList.getNum() > 0){
			sql.append(" and o.num = ?");
			list.add(intoList.getNum());
		}
		if(StringUtils.isNotEmpty(intoList.getUnit())){
			sql.append(" and o.unit like ?");
			list.add("%"+intoList.getUnit()+"%");
		}
		if(intoList.getPriceTotal() != null && intoList.getPriceTotal() > 0){
			sql.append(" and o.price_total = ?");
			list.add(intoList.getPriceTotal());
		}
		if(intoList.getPriceInto() != null && intoList.getPriceInto() > 0){
			sql.append(" and o.price_into = ?");
			list.add(intoList.getPriceInto());
		}
		if(intoList.getVersion() != null && intoList.getVersion() > 0){
			sql.append(" and o.version = ?");
			list.add(intoList.getVersion());
		}
		if(StringUtils.isNotEmpty(intoList.getState())){
			sql.append(" and o.state like ?");
			list.add("%"+intoList.getState()+"%");
		}
		if(intoList.getNumOut() != null && intoList.getNumOut() > 0){
			sql.append(" and o.num_out = ?");
			list.add(intoList.getNumOut());
		}
		wap.setWhere(sql.toString());
		wap.setParas(list.toArray());
		return wap;
	}
}
