package com.xiaoan.wlt.model.base;

import com.xiaoan.wlt.common.jfinal.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDialingStatus<M extends BaseDialingStatus<M>> extends BaseModel<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public void setVersion(java.lang.Integer version) {
		set("version", version);
	}

	public java.lang.Integer getVersion() {
		return get("version");
	}

	public void setCalled(java.lang.String called) {
		set("called", called);
	}

	public java.lang.String getCalled() {
		return get("called");
	}

	public void setCaller(java.lang.String caller) {
		set("caller", caller);
	}

	public java.lang.String getCaller() {
		return get("caller");
	}

	public void setDescribes(java.lang.String describes) {
		set("describes", describes);
	}

	public java.lang.String getDescribes() {
		return get("describes");
	}

	public void setDialStatus(java.lang.String dialStatus) {
		set("dialStatus", dialStatus);
	}

	public java.lang.String getDialStatus() {
		return get("dialStatus");
	}

	public void setHoldTime(java.lang.Long holdTime) {
		set("holdTime", holdTime);
	}

	public java.lang.Long getHoldTime() {
		return get("holdTime");
	}

	public void setIsCallBack(java.lang.String isCallBack) {
		set("isCallBack", isCallBack);
	}

	public java.lang.String getIsCallBack() {
		return get("isCallBack");
	}

	public void setResult(java.lang.String result) {
		set("result", result);
	}

	public java.lang.String getResult() {
		return get("result");
	}

	public void setSessionId(java.lang.String sessionId) {
		set("sessionId", sessionId);
	}

	public java.lang.String getSessionId() {
		return get("sessionId");
	}

	public void setStartTime(java.util.Date startTime) {
		set("startTime", startTime);
	}

	public java.util.Date getStartTime() {
		return get("startTime");
	}

	public void setCustAcntId(java.lang.Long custAcntId) {
		set("custAcntId", custAcntId);
	}

	public java.lang.Long getCustAcntId() {
		return get("custAcntId");
	}

	public void setIsStatusCallBack(java.lang.String isStatusCallBack) {
		set("isStatusCallBack", isStatusCallBack);
	}

	public java.lang.String getIsStatusCallBack() {
		return get("isStatusCallBack");
	}

}
