package com.xiaoan.wlt.model.base.erp.jxc;

import com.xiaoan.wlt.common.jfinal.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

import org.apache.commons.lang3.StringUtils;

import com.xiaoan.wlt.common.WhereAndParas;

import java.util.ArrayList;

import java.util.List;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSupplier<M extends BaseSupplier<M>> extends BaseModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setSId(java.lang.Integer sId) {
		set("s_id", sId);
	}

	public java.lang.Integer getSId() {
		return get("s_id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}

	public java.lang.String getMobile() {
		return get("mobile");
	}

	public void setAddr(java.lang.String addr) {
		set("addr", addr);
	}

	public java.lang.String getAddr() {
		return get("addr");
	}

	public void setAppellation(java.lang.String appellation) {
		set("appellation", appellation);
	}

	public java.lang.String getAppellation() {
		return get("appellation");
	}

	public void setAmount(java.lang.Double amount) {
		set("amount", amount);
	}

	public java.lang.Double getAmount() {
		return get("amount");
	}

	public void setState(java.lang.String state) {
		set("state", state);
	}

	public java.lang.String getState() {
		return get("state");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setRemarks(java.lang.String remarks) {
		set("remarks", remarks);
	}

	public java.lang.String getRemarks() {
		return get("remarks");
	}

	public void setVersion(java.lang.Integer version) {
		set("version", version);
	}

	public java.lang.Integer getVersion() {
		return get("version");
	}

	public static final String TABLE = " erp_jxc_supplier ";
	public WhereAndParas getWhereAndParas(BaseSupplier supplier){
		StringBuffer sql = new StringBuffer();
		List<Object> list = new ArrayList<Object>();
		WhereAndParas wap = new WhereAndParas();
		if(supplier.getId() != null && supplier.getId() > 0){
			sql.append(" and o.id = ?");
			list.add(supplier.getId());
		}
		if(supplier.getSId() != null && supplier.getSId() > 0){
			sql.append(" and o.s_id = ?");
			list.add(supplier.getSId());
		}
		if(StringUtils.isNotEmpty(supplier.getName())){
			sql.append(" and o.name like ?");
			list.add("%"+supplier.getName()+"%");
		}
		if(StringUtils.isNotEmpty(supplier.getMobile())){
			sql.append(" and o.mobile like ?");
			list.add("%"+supplier.getMobile()+"%");
		}
		if(StringUtils.isNotEmpty(supplier.getAddr())){
			sql.append(" and o.addr like ?");
			list.add("%"+supplier.getAddr()+"%");
		}
		if(StringUtils.isNotEmpty(supplier.getAppellation())){
			sql.append(" and o.appellation like ?");
			list.add("%"+supplier.getAppellation()+"%");
		}
		if(supplier.getAmount() != null && supplier.getAmount() > 0){
			sql.append(" and o.amount = ?");
			list.add(supplier.getAmount());
		}
		if(StringUtils.isNotEmpty(supplier.getState())){
			sql.append(" and o.state like ?");
			list.add("%"+supplier.getState()+"%");
		}
		if(StringUtils.isNotEmpty(supplier.getRemarks())){
			sql.append(" and o.remarks like ?");
			list.add("%"+supplier.getRemarks()+"%");
		}
		if(supplier.getVersion() != null && supplier.getVersion() > 0){
			sql.append(" and o.version = ?");
			list.add(supplier.getVersion());
		}
		wap.setWhere(sql.toString());
		wap.setParas(list.toArray());
		return wap;
	}
}
