package com.xiaoan.wlt.model.base.erp.jxc;

import com.xiaoan.wlt.common.jfinal.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

import org.apache.commons.lang3.StringUtils;

import com.xiaoan.wlt.common.WhereAndParas;

import java.util.ArrayList;

import java.util.List;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseInto<M extends BaseInto<M>> extends BaseModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setSId(java.lang.Integer sId) {
		set("s_id", sId);
	}

	public java.lang.Integer getSId() {
		return get("s_id");
	}

	public void setCode(java.lang.String code) {
		set("code", code);
	}

	public java.lang.String getCode() {
		return get("code");
	}

	public void setSupplierId(java.lang.Integer supplierId) {
		set("supplier_id", supplierId);
	}

	public java.lang.Integer getSupplierId() {
		return get("supplier_id");
	}

	public void setIntoUser(java.lang.String intoUser) {
		set("into_user", intoUser);
	}

	public java.lang.String getIntoUser() {
		return get("into_user");
	}

	public void setIntoTime(java.util.Date intoTime) {
		set("into_time", intoTime);
	}

	public java.util.Date getIntoTime() {
		return get("into_time");
	}

	public void setState(java.lang.String state) {
		set("state", state);
	}

	public java.lang.String getState() {
		return get("state");
	}

	public void setPriceTotal(java.lang.Double priceTotal) {
		set("price_total", priceTotal);
	}

	public java.lang.Double getPriceTotal() {
		return get("price_total");
	}

	public void setRemarks(java.lang.String remarks) {
		set("remarks", remarks);
	}

	public java.lang.String getRemarks() {
		return get("remarks");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setVersion(java.lang.Integer version) {
		set("version", version);
	}

	public java.lang.Integer getVersion() {
		return get("version");
	}

	public void setDepotId(java.lang.Integer depotId) {
		set("depot_id", depotId);
	}

	public java.lang.Integer getDepotId() {
		return get("depot_id");
	}

	public static final String TABLE = " erp_jxc_into ";
	public WhereAndParas getWhereAndParas(BaseInto into){
		StringBuffer sql = new StringBuffer();
		List<Object> list = new ArrayList<Object>();
		WhereAndParas wap = new WhereAndParas();
		if(into.getId() != null && into.getId() > 0){
			sql.append(" and o.id = ?");
			list.add(into.getId());
		}
		if(into.getSId() != null && into.getSId() > 0){
			sql.append(" and o.s_id = ?");
			list.add(into.getSId());
		}
		if(StringUtils.isNotEmpty(into.getCode())){
			sql.append(" and o.code like ?");
			list.add("%"+into.getCode()+"%");
		}
		if(into.getSupplierId() != null && into.getSupplierId() > 0){
			sql.append(" and o.supplier_id = ?");
			list.add(into.getSupplierId());
		}
		if(StringUtils.isNotEmpty(into.getIntoUser())){
			sql.append(" and o.into_user like ?");
			list.add("%"+into.getIntoUser()+"%");
		}
		if(StringUtils.isNotEmpty(into.getState())){
			sql.append(" and o.state like ?");
			list.add("%"+into.getState()+"%");
		}
		if(into.getPriceTotal() != null && into.getPriceTotal() > 0){
			sql.append(" and o.price_total = ?");
			list.add(into.getPriceTotal());
		}
		if(StringUtils.isNotEmpty(into.getRemarks())){
			sql.append(" and o.remarks like ?");
			list.add("%"+into.getRemarks()+"%");
		}
		if(into.getVersion() != null && into.getVersion() > 0){
			sql.append(" and o.version = ?");
			list.add(into.getVersion());
		}
		if(into.getDepotId() != null && into.getDepotId() > 0){
			sql.append(" and o.depot_id = ?");
			list.add(into.getDepotId());
		}
		wap.setWhere(sql.toString());
		wap.setParas(list.toArray());
		return wap;
	}
}
