package com.xiaoan.wlt.model.base.zyk;

import com.xiaoan.wlt.common.jfinal.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

import org.apache.commons.lang3.StringUtils;

import com.xiaoan.wlt.common.WhereAndParas;

import java.util.ArrayList;

import java.util.List;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseActLog<M extends BaseActLog<M>> extends BaseModel<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public void setActTime(java.util.Date actTime) {
		set("actTime", actTime);
	}

	public java.util.Date getActTime() {
		return get("actTime");
	}

	public void setVersion(java.lang.Integer version) {
		set("version", version);
	}

	public java.lang.Integer getVersion() {
		return get("version");
	}

	public void setResourceType(java.lang.String resourceType) {
		set("resourceType", resourceType);
	}

	public java.lang.String getResourceType() {
		return get("resourceType");
	}

	public void setResourceId(java.lang.Long resourceId) {
		set("resourceId", resourceId);
	}

	public java.lang.Long getResourceId() {
		return get("resourceId");
	}

	public void setAct(java.lang.String act) {
		set("act", act);
	}

	public java.lang.String getAct() {
		return get("act");
	}

	public void setUserId(java.lang.Long userId) {
		set("userId", userId);
	}

	public java.lang.Long getUserId() {
		return get("userId");
	}

	public static final String TABLE = " zyk_act_log ";
	public WhereAndParas getWhereAndParas(BaseActLog actLog){
		StringBuffer sql = new StringBuffer();
		List<Object> list = new ArrayList<Object>();
		WhereAndParas wap = new WhereAndParas();
		if(actLog.getId() != null && actLog.getId() > 0){
			sql.append(" and o.id = ?");
			list.add(actLog.getId());
		}
		if(actLog.getVersion() != null && actLog.getVersion() > 0){
			sql.append(" and o.version = ?");
			list.add(actLog.getVersion());
		}
		if(StringUtils.isNotEmpty(actLog.getResourceType())){
			sql.append(" and o.resourceType like ?");
			list.add("%"+actLog.getResourceType()+"%");
		}
		if(actLog.getResourceId() != null && actLog.getResourceId() > 0){
			sql.append(" and o.resourceId = ?");
			list.add(actLog.getResourceId());
		}
		if(StringUtils.isNotEmpty(actLog.getAct())){
			sql.append(" and o.act like ?");
			list.add("%"+actLog.getAct()+"%");
		}
		if(actLog.getUserId() != null && actLog.getUserId() > 0){
			sql.append(" and o.userId = ?");
			list.add(actLog.getUserId());
		}
		wap.setWhere(sql.toString());
		wap.setParas(list.toArray());
		return wap;
	}
}
