package com.xiaoan.wlt.model.base.zyk;

import com.xiaoan.wlt.common.jfinal.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

import org.apache.commons.lang3.StringUtils;

import com.xiaoan.wlt.common.WhereAndParas;

import java.util.ArrayList;

import java.util.List;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseShopsResource<M extends BaseShopsResource<M>> extends BaseModel<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public void setVersion(java.lang.Integer version) {
		set("version", version);
	}

	public java.lang.Integer getVersion() {
		return get("version");
	}

	public void setShopsId(java.lang.Long shopsId) {
		set("shopsId", shopsId);
	}

	public java.lang.Long getShopsId() {
		return get("shopsId");
	}

	public void setShopsName(java.lang.String shopsName) {
		set("shopsName", shopsName);
	}

	public java.lang.String getShopsName() {
		return get("shopsName");
	}

	public void setMainPic(java.lang.String mainPic) {
		set("mainPic", mainPic);
	}

	public java.lang.String getMainPic() {
		return get("mainPic");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}

	public java.lang.String getDescription() {
		return get("description");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public void setRate(java.lang.Integer rate) {
		set("rate", rate);
	}

	public java.lang.Integer getRate() {
		return get("rate");
	}

	public void setHits(java.lang.Integer hits) {
		set("hits", hits);
	}

	public java.lang.Integer getHits() {
		return get("hits");
	}

	public void setVoteUp(java.lang.Integer voteUp) {
		set("voteUp", voteUp);
	}

	public java.lang.Integer getVoteUp() {
		return get("voteUp");
	}

	public void setCategory(java.lang.Long category) {
		set("category", category);
	}

	public java.lang.Long getCategory() {
		return get("category");
	}

	public void setTemplateId(java.lang.Long templateId) {
		set("templateId", templateId);
	}

	public java.lang.Long getTemplateId() {
		return get("templateId");
	}

	public void setState(java.lang.String state) {
		set("state", state);
	}

	public java.lang.String getState() {
		return get("state");
	}

	public static final String TABLE = " zyk_shops_resource ";
	public WhereAndParas getWhereAndParas(BaseShopsResource shopsResource){
		StringBuffer sql = new StringBuffer();
		List<Object> list = new ArrayList<Object>();
		WhereAndParas wap = new WhereAndParas();
		if(shopsResource.getId() != null && shopsResource.getId() > 0){
			sql.append(" and o.id = ?");
			list.add(shopsResource.getId());
		}
		if(shopsResource.getVersion() != null && shopsResource.getVersion() > 0){
			sql.append(" and o.version = ?");
			list.add(shopsResource.getVersion());
		}
		if(shopsResource.getShopsId() != null && shopsResource.getShopsId() > 0){
			sql.append(" and o.shopsId = ?");
			list.add(shopsResource.getShopsId());
		}
		if(StringUtils.isNotEmpty(shopsResource.getShopsName())){
			sql.append(" and o.shopsName like ?");
			list.add("%"+shopsResource.getShopsName()+"%");
		}
		if(StringUtils.isNotEmpty(shopsResource.getMainPic())){
			sql.append(" and o.mainPic like ?");
			list.add("%"+shopsResource.getMainPic()+"%");
		}
		if(StringUtils.isNotEmpty(shopsResource.getTitle())){
			sql.append(" and o.title like ?");
			list.add("%"+shopsResource.getTitle()+"%");
		}
		if(StringUtils.isNotEmpty(shopsResource.getDescription())){
			sql.append(" and o.description like ?");
			list.add("%"+shopsResource.getDescription()+"%");
		}
		if(StringUtils.isNotEmpty(shopsResource.getContent())){
			sql.append(" and o.content like ?");
			list.add("%"+shopsResource.getContent()+"%");
		}
		if(shopsResource.getRate() != null && shopsResource.getRate() > 0){
			sql.append(" and o.rate = ?");
			list.add(shopsResource.getRate());
		}
		if(shopsResource.getHits() != null && shopsResource.getHits() > 0){
			sql.append(" and o.hits = ?");
			list.add(shopsResource.getHits());
		}
		if(shopsResource.getVoteUp() != null && shopsResource.getVoteUp() > 0){
			sql.append(" and o.voteUp = ?");
			list.add(shopsResource.getVoteUp());
		}
		if(shopsResource.getCategory() != null && shopsResource.getCategory() > 0){
			sql.append(" and o.category = ?");
			list.add(shopsResource.getCategory());
		}
		if(shopsResource.getTemplateId() != null && shopsResource.getTemplateId() > 0){
			sql.append(" and o.templateId = ?");
			list.add(shopsResource.getTemplateId());
		}
		if(StringUtils.isNotEmpty(shopsResource.getState())){
			sql.append(" and o.state like ?");
			list.add("%"+shopsResource.getState()+"%");
		}
		wap.setWhere(sql.toString());
		wap.setParas(list.toArray());
		return wap;
	}
}
